export const day1Postac = `
Bł. Pierre Claverie (1938-1996)

Pierre Claverie urodził się w we francuskiej rodzinie w Al-gierze w 1938 r. W dorosłym życiu wyznał: „Dzieciństwo spędziłem w Algierze, w popularnej dzielnicy tego kosmopolitycznego, śródziemnomorskiego miasta. W przeciwieństwie do innych Europejczyków, urodzonych na wsi lub w małych miasteczkach, nigdy nie miałem arabskich przyjaciół. Nie byliśmy rasistami, po prostu obojętni, ignorowaliśmy większość populacji tego kraju. Arabowie byli częścią krajobrazu naszych wycieczek, tła naszych spotkań i naszego życia. Nigdy nie byli towarzyszami... Musiałem wysłuchać wielu kazań na temat miłości bliźniego, ponieważ byłem chrześcijaninem i harcerzem, ale nigdy nie zdawałem sobie sprawy, że Arabowie też byli moimi sąsiadami. Potrzeba było wojny, żeby ta bańka pękła”.

Odczuwając głos powołania, Pierre wstąpił do dominikanów. Studiował w Le Saulchoir u najlepszych dominikańskich teologów. Wtedy też zyskał solidną formację intelektualną i duchową, która później okazała się dla niego bezcenna. Wyświęcony na kapłana, z radością zgodził się dołączyć do małej wspólnoty dominikańskiej w Algierze. Wraz z braćmi żył na co dzień dominikańskim charyzmatem w kraju zdominowanym przez muzułmanów. Wciąż zastanawiał się też nad tym, jaką rolę ma do odegrania Kościół w tamtejszych realiach. Pilnie uczył się języka arabskiego. Wkrótce opanował go tak dobrze, że był w stanie uczyć go innych. Przede wszystkim jednak odkrywał rzeczywistość Algierii, poznawał nowych ludzi, budował serdeczne relacje z muzułmanami. Wielu z nich należało do jego bliskich przyjaciół.

W tym czasie kraj rozpoczął odbudowę po bardzo krwawej wojnie (1954-1962). Jednym z podstawowych wyzwań stała się edukacja i formacja liderów życia społecznego. Pierre Claverie wraz z innymi kapłanami i zakonnikami całkowicie oddali się temu zadaniu. Był to bardzo szczęśliwy okres jego życia. Solidna formacja intelektualna pozwalała mu też aktywnie uczestniczyć w refleksji teologicznej Kościoła, który musiał na nowo przemyśleć swoje zadanie w powojennej rzeczywistości. Pierre odkrywał, że nie mogąc ewangelizować społeczności muzułmańskiej, powinien zaoferować jej ewangeliczne świadectwo i bezinteresowną miłość. Dostrzegał też coraz bardziej, że Kościół musi jej pomóc leczyć rany odziedziczone z przeszłości kolonialnej i wojny wyzwoleńczej. W roku 1981 jego silna osobowość i charyzma przyniosły mu nominację na biskupa Oranu. W czasie swojej biskupiej konsekracji mocno podkreślał swą wdzięczność wobec algierskich przyjaciół. Zaznaczył, że dzięki nim poznał język, kulturę i mentalność. Przestał żyć jak obcokrajowiec w swoim kraju. Nauczył się braterskiej przyjaźni, dzięki której komunikują się narody i religie.

Diecezja, którą zaczął kierować, liczyła niewielu wiernych, ale była za to międzynarodowa. Bp Pierre od samego początku podjął się zadania budowania w niej prawdziwej wspólnoty. Zależało mu na harmonijnej współpracy nie tylko między chrześcijanami pochodzącymi z różnych krajów, ale i z muzułmańskimi przyjaciółmi Kościoła. Znając potrzeby lokalnej społeczności, zdecydował, aby udostępnić pomieszczenia i obiekty swojej diecezji na potrzeby biblioteki, ośrodka dla osób niepełnosprawnych itd.

Biskup Claverie nawiązywał z muzułmanami relacje oparte na zaufaniu i przyjaźni. Zdecydowanie przeciwstawiał się wszelkiej politycznej hipokryzji. Bez wahania podkreślał, że „w całokształcie stosunków między chrześcijanami i muzułmanami, dialog nie zawsze był regułą”, a wręcz przeciw-nie: „dominowały kontrowersje i konflikty”.

Począwszy od 1990 r., Algieria pogrążyła się w chaosie i przemocy. Po dwudziestu pięciu latach jednopartyjnego reżimu pojawiły się liczne radykalne partie muzułmańskie. W czasie wyborów parlamentarnych w 1992 r. zebrały one większość głosów i były prawie u władzy, ale reżim wojskowy przerwał proces wyborczy. Fundamentalistyczni fanatycy próbowali dojść do władzy siłą. Zaczęli od mordowania setek przedstawicieli państwa, sędziów, policjantów itd. Następnie eliminowali brutalnie znane postaci otwartego społeczeństwa obywatelskiego – dziennikarzy i pisarzy. W końcu wzięli się za obcokrajowców. Morderstwo pierwszych dwóch chrześcijańskich duchownych w maju 1994 r. było traumą dla wszystkich. Zabicie siedmiu mnichów trapistów w 1996 r. wywołało skandal u zdecydowanej większości muzułmanów. Bp Pierre Claverie nie tylko zdecydował się pozostać, ale przede wszystkim odważnie zabierał głos, publicznie opowiadając się za „pluralistycznym, niewykluczającym człowieczeństwem”. Został zamordowany 1 sierpnia 1996 r. wraz z muzułmańskim przyjacielem Mohamedem Bouchikhi, który zdecydował się pozostać z nim pomimo ryzyka. Jego śmierć wstrząsnęła chrześcijanami, ale także wieloma algierskimi muzułmanami. Na jego pogrzebie ci ostatni twierdzili, że przyszli opłakiwać tego, który był również „ich” biskupem.
`;