export const day2Postac = `
Bł. Benedict Daswa (1946-1990)

Benedykt Daswa urodził się 16 czerwca 1946 r. Jako młody mężczyzna założył rodzinę. Był prawdziwym wzorem męża i ojca całkowicie oddanego ideałowi rodziny jako „Kościoła domowego”. Jako szanowany i oddany dyrektor szkoły, motywował i szkolił swój personel, aby zapewnić uczniom możliwie najlepszą edukację, angażował rodziców jako współpracowników w całym procesie edukacyjnym. Był przewodnikiem dla młodych ludzi i spędzał z nimi wiele godzin i weekendów. Będąc zmotywowanym sportowcem, Benedykt zaszczepiał w nich wartości ciężkiej pracy, dyscypliny, ducha fair play i pracy zespołowej.

Kiedy powstała pierwsza Parafialna Rada Duszpasterska, został wybrany jej przewodniczącym. Uczył katechizmu dzieci i dorosłych, prowadził niedzielne uroczystości pod nieobecność księdza, odwiedzał chorych oraz pomagał biednym i potrzebującym. Przy parafii pomógł założyć przedszkole.

Benedykt wykazywał się duchem prawdziwej chrześcijańskiej miłości, szacunku, hojności, uczciwości i wolności. Ale przede wszystkim, w każdej sytuacji, był człowiekiem modlitwy. Jego życie duchowe było nieustannie karmione przez Eucharystię i słowo Boże. Nigdy nie wstydził się przyznać do swojej wielkiej wiary w Boga: to On dawał mu siłę. Chciał, aby wierzący byli dumni ze swojej wiary i brali prawdziwą odpowiedzialność za Kościół. Oznaczało to między innymi pracę na rzecz powołań kapłańskich i zakonnych, aktywność w życiu parafii i wspieranie jej finansowo.

W sferze publicznej Benedykt nie ukrywał swojego stanowiska wobec czarów, magii i morderstw rytualnych, których nie mógł dłużej akceptować. Przede wszystkim nie mógł pogodzić się z tym, że niewinna osoba mogła być zabita lub wygnana z wioski jako rzekomy czarownik. Zdawał sobie sprawę, że uwolnieni z tych praktyk młodzi ludzie podejmą osobistą odpowiedzialność za swoje życie. Pracował nad tym zarówno w społeczności lokalnej jako doradca i konsultant wójta, a także w społeczności kościelnej jako katecheta i lider modlitwy. Jego stanowisko przeciwko czarom nie było zbyt popularne, ponieważ sprzeciwiał się rzeczywistości głęboko zakorzenionej w lokalnej kulturze. Owszem, byli inni, którzy, podobnie jak Benedykt, uważali czary za owoc zła, strachu, nieufności i przemocy. Co więcej, wierzyli, że ludzie powinni porzucić tę praktykę. Jednak osoby te, w tym także duchowni, milczeli z obawy przed represjami. Benedykt był inny i nigdy nie szedł na kompromis. Mówił otwarcie i stanowczo, sprzeciwiając się ludziom, którzy uciekali się do czarów. Zawsze trzymał się zasad swojej wiary chrześcijańskiej. Bronił ludzi, którzy odmawiali płacenia za konsultacje z szamanem, nie chcąc, by płacili za coś, co nie istnieje.

25 stycznia 1990 r. wioskę Benedykta nawiedziła burza, podczas której w dachy niektórych chat uderzyły pioruny i spowodowały pożar. W najbliższą niedzielę wódz wioski zwołał spotkanie rady, aby zająć się tą sprawą. Zanim przybył na nie Benedykt, zdecydowano, że niektórzy członkowie społeczności powinni zwrócić się do szamana, aby wskazać osobę, która „wysłała” pioruny. Benedykt próbował zmienić ich zdanie, tłumacząc, że decyzja ta doprowadzi do śmierci niewinnych osób. Spotkanie zakończyło się w napięciu, a starsi podjęli stanowczą decyzję, by zaprzestać współpracy z Benedyktem. Według lokalnych zwyczajów należało bowiem wyeliminować nie tylko winnych klęski, ale i osoby, które ich chroniły. Stało się to 2 lutego 1990 r., w święto Ofiarowania Pańskiego – Benedykt został zabity.

W pamięci zapisał się jako osoba, która potrafiła mą-drze przyjmować to, co było dobre w lokalnej kulturze, a jednocześnie odważnie kwestionować te elementy kulturowe, które utrudniały życie zgodne z Ewangelią. W wiejskiej, tradycyjnej społeczności afrykańskiej w apartheidowej Republi-ce Południowej Afryki, dał prorocze świadectwo pełnej szacunku postawy wobec równości kobiet. Wierzył w wierne, monogamiczne małżeństwo, które znajduje swój pełny wyraz w chrześcijańskim sakramencie. Jak świadczą jego dzieci, nigdy nie wstydził się pomagać swojej żonie w pracach domowych zwyczajowo zarezerwowanych dla kobiet. Modlił się z rodziną każdego dnia i zachęcał wszystkich rodziców do modlitwy ze swoimi dziećmi. Organizował regularne spotkania rodzinne i działał jako mediator i doradca dla par znajdujących się w trudnej sytuacji. Przede wszystkim, był człowiekiem pokornym, który zawsze szukał dialogu. Nigdy nie wy-parł się swojej afrykańskiej kultury, ale przyjął jej najlepsze aspekty, oczyszczone z zabobonów i dojrzałe. Jego brutalna śmierć przez pobicie i ukamienowanie uczyniła go bohaterem. Przykład, jaki dał jako członek rodziny, sumienny katecheta, troskliwy nauczyciel – jest tym, co wielu mieszkańców RPA może dziś uważać za najważniejsze dziedzictwo jego życia. Papież Franciszek w swoim dekrecie beatyfikacyjnym opisał go między innymi takimi słowami: „pilny katecheta, troskliwy nauczyciel, świadek Ewangelii aż do przelania krwi”. Benedykt został beatyfikowany 13 września 1990 r.
`;