export const day3Postac = `
Wanda Błeńska (1911-2014)

Wanda Maria Błeńska urodziła się 30 października 1911 r. w Poznaniu. 9 grudnia tego samego roku została ochrzczona. Ze względu na chorobę matki, rodzina przeniosła się do Puszczykowa, ale stan chorej nie poprawiał się. Mając zaledwie piętnaście miesięcy mała Wanda została bez matki. W 1920 r. wraz z ojcem i bratem Romanem przeprowadziła się ponownie, tym razem do Torunia. Tam przystąpiła do I Komunii św. i uczęszczała do państwowego gimnazjum żeńskiego. W 1928 r. zdała egzamin maturalny i otrzymała świadectwo dojrzałości. Zrobiła pierwszy krok w kierunku realizacji swoich marzeń, wracając do Poznania na studia na Wydziale Lekarskim. Choć na wyjazd na misje musiała poczekać jeszcze wiele lat, to duchem misyjnym żyła już w Poznaniu. Początkowo należała do Sekcji Misyjnej w ramach ruchu Sodalicji Mariańskiej. 20 stycznia 1927 r. w auli Uniwersytetu Poznańskiego, w obecności kard. Augusta Hlonda, zainaugurowano działalność pierwszego Akademickiego Koła Misjologicznego. Liczyło ono wówczas około 150 osób. Wanda aktywnie uczestniczyła w organizacji i animacji tegoż ruchu.

Przez lata brała udział w krajowych i międzynarodowych kongresach misyjnych. W 1931 r. została członkiem Zarządu Poznańskiej Grupy Misyjnej. Brała również udział w redagowaniu „Annales Missiologicae”, pierwszego czasopisma misyjnego w Polsce. Po ukończeniu studiów wróciła do Torunia, gdzie rozpoczęła pracę najpierw w szpitalu miejskim, a następnie, do końca wojny, w Państwowym Zakładzie Higieny. W 1942 r. wstąpiła w szeregi tajnej organizacji wojskowej Gryf Pomorski, włączonej później do Armii Krajowej. W dniu swoich imienin, 23 czerwca 1944 r., Wanda została aresztowana za działalność konspiracyjną. W więzieniu została skazana na karę śmierci, ale po ponad dwóch miesiącach została zwolniona. Po wojnie Błeńska objęła stanowisko dyrektora jednego ze szpitali w Toruniu i pracowała w Zakładzie Higieny w Gdańsku. W 1946 r. postanowiła odwiedzić swojego umierającego brata Romana, który przebywał w Niemczech. Po śmierci Romana nie mogła wrócić do Polski. Pozostała w Niemczech, gdzie pracowała w polskich szpitalach wojskowych. W 1947 r. wzięła udział w kursie medycyny tropikalnej w Hamburgu. Następnie przeniosła się do Anglii, gdzie kontynuowała swoją edukację w dziedzinie medycyny tropikalnej i została przyjęta do Królewskiego Towarzystwa Medycyny Tropikalnej i Higieny w Londynie. To tam poznała misjonarza ze Zgromadzenia Ojców Białych, który opowiedział jej o planach budowy kolonii dla trędowatych w Fort Portal.

W 1950 r. dr Błeńska otrzymała od lokalnego biskupa zaproszenie do Ugandy i w marcu tego samego roku rozpoczęła pracę. Rok później przybyła do Buluby nad Jeziorem Wiktorii i podjęła pracę w szpitalu św. Franciszka, gdzie jako lekarz i świecka misjonarka pozostała przez kolejnych czterdzieści lat. Na początku warunki pracy były opłakane, ale Wanda zmodernizowała instytucję, doprowadzając do wysokiego standardu leczenia i opieki nad pacjentami. W 1956 r. założyła centrum szkoleniowe dla asystentów medycznych w zakresie diagnozowania i leczenia trądu, które dziś nosi jej imię. Uczyła wielu studentów w różnych krajach afrykańskich, uczestniczyła w Międzynarodowych Kongresach Lekarzy Trądu i stała się jednym z najbardziej wykwalifikowanych specjalistów w leczeniu tej choroby na świecie.

 Wanda Błeńska podbiła serca Ugandyjczyków nie tylko swoimi umiejętnościami zawodowymi, ale także podejściem do chorych. Nazywano ją „Matką Trędowatych”. Dzięki swojej pracy pomogła przezwyciężyć społeczne napiętnowanie trędowatych i podjęła wiele działań, aby przywrócić im godność. Badała ich bez rękawiczek, ponieważ nie chciała, aby pacjenci czuli się dyskryminowani. Zakładała je tylko wtedy, gdy rana była otwarta lub gdy operowała. Po latach wspominała: „Przede wszystkim chciałam sprawić, aby zmniejszyć ich strach. Jak każda choroba, trąd również wymaga oswojenia. Ci pacjenci są biedni”. Wanda Błeńska powróciła do Polski w 1992 r., ale jeszcze przez dwa lata podróżowała między dwiema ojczyznami (Polską i Ugandą). Ostatecznie w 1994 r. osiedliła się w Poznaniu. Po raz ostatni pojechała do Ugandy w 2006 r. Pomimo podeszłego wieku, do końca życia uczestniczyła w życiu misyjnym Kościoła. Do 93. roku życia wykładała w Centrum Formacji Misyjnej w Warszawie. Przez lata odwiedzała szkoły, parafie, ośrodki duszpasterskie i grupy misyjne, animując zwłaszcza dzieci i młodzież. Oprócz uczestniczenia w konferencjach i zjazdach misyjnych, organizowała pomoc medyczną i finansową dla misjonarzy. Była w grupie inicjatorów fundacji Redemptoris Missio. Otrzymała liczne nagrody i odznaczenia kościelne oraz państwowe, między innymi: Krzyż Pro Ecclesia et Pontefice, Medal św. Sylwestra, honorowe obywatelstwo Ugandy, tytuł Honoris Causa Akademii Medycznej w Poznaniu oraz Order Uśmiechu. Akademickie Koło Misjologiczne, reaktywowane w 2002 r., nosi imię Wandy Błeńskiej i co roku wysyła młodych ludzi na doświadczenia misyjne. 7 czerwca 2003 r. Instytut Misjonarzy Świeckich przy Konferencji Episkopatu Polski został również nazwany jej imieniem. Wanda Błeńska zmarła w Poznaniu 27 listopada 2014 r. w wieku 103 lat. Obecnie Archidiecezja Poznańska zbiera wszelkie materiały i świadectwa dotyczące jej życia i świętości.
`;