export const day4Postac = `
Bł. Lucien Botovasoa (1908-1947)

Lucien Botovasoa urodził się w 1908 r. w Vohipeno, małej wiosce na południowo-wschodnim wybrzeżu Madagaskaru. Jego rodzice byli biednymi rolnikami, jak wielu innych w tym regionie. Wyznawali tradycyjną religię, ale byli otwarci i tolerancyjni. Kiedy mieszkańcy wioski odkryli wiarę chrześcijańską, wielu nawróciło się i poprosiło o chrzest. Wśród nich był Botovasoa.

Został ochrzczony 15 kwietnia 1922 r. w wieku trzynastu lat. Lucien chciał żyć swoją wiarą z zaangażowaniem i powagą. Ideałem było dla niego bycie dobrym chrześcijaninem i apostołem Jezusa w sercu świata. Po uzyskaniu tytułu magistra powrócił do Vohipeno jako nauczyciel i wicedyrektor szkoły parafialnej. Był nauczycielem wyjątkowym, kompetentnym i sumiennym. Z zapałem i łagodnością wyjaśniał uczniom wszystkie trudne tematy. Równocześnie troszczył się o edukację religijną. Katechizował zarówno w godzinach szkolnych, jak i po lekcjach. Każdego wieczoru czytał historie świętych tym, którzy sobie tego życzyli. Najbardziej lubił życiorysy męczenników. Opowiadał je z zapałem, który rozpalał całą jego duszę. W 1930 r. Lucien wziął ślub kościelny z Suzanne Soazana. Doczekali się ośmiorga dzieci, z których przeżyło tylko pięcioro. Lucien kochał swoje dzieci, kształcił je i uczył modlitwy. Spędzał też dużo czasu, opiekując się dziećmi innych, odwiedzając chorych, animując różne grupy poprzez objaśnianie katechizmu. Miejscem, gdzie najczęściej go widywano, był kościół: modlił się nie tylko podczas niedzielnych mszy św., ale także każdego ranka. Grał też na fisharmonii i kierował chórem, Kiedy odkrył Franciszkański Zakon Świeckich założył w swojej parafii jego pierwszą wspólnotę. Coraz bardziej Lucien zaczął wyróżniać się w pobożności i prostocie. Każdej nocy wstawał kilka razy, aby modlić się na kolanach u stóp łóżka, a o szóstej szedł do kościoła na godzinę medytacji przed tabernakulum. W środy i piątki pościł.

W tym czasie, w roku 1946, na Madagaskarze odbywały się wybory. Dwie partie polityczne chciały mieć Luciena jako swojego kandydata. Jednak on kategorycznie odmówił: „Wasza polityka karmi się kłamstwami i skończy się tylko krwią”. Wkrótce tak się i stało. Rozpoczęły się masakry trwające cały Wielki Tydzień. Spalono osiemnaście kościołów i pięć szkół. Oczywiście w dzień Wielkanocy nie można było sprawować Eucharystii w kościele parafialnym. W tym czasie Lucien i wielu innych schroniło się w lesie. W drugą niedzielę Wielkanocy udało mu się zgromadzić wszystkich uchodźców na wspólnej modlitwie, w której uczestniczyli katolicy, protestanci i muzułmanie. Lucien, nawiązując do Ewangelii, wzywał wszystkich do ożywienia wiary i odwagi, by stawić czoła męczeństwu, jeśli będzie to konieczne. Prze-mawiał i prowadził śpiew z wielką radością i pogodą ducha. 17 kwietnia 1947 r. król Tsimihono, lokalny przywódca Mal-gaskiego Ruchu Odnowy Demokratycznej (MDRM) zapro-ponował Lucienowi, by został on sekretarzem tejże partii. Gdyby przyjął stanowisko sekretarza MDRM, uratowałby z pewnością swoje życie. Ale odpowiedział: „Zabijacie, palicie kościoły, zabraniacie modlitwy, depczecie krzyże, niszczycie święte obrazy, różańce i szkaplerze, chcecie zbezcześcić nasz kościół, zamieniając go w salę taneczną – to brudna robota. Wiesz, jak ważna jest dla mnie religia: nie mogę dla ciebie pracować”. W międzyczasie Lucien ostrzegł swoją żonę, że zostanie potępiony. Suzanne chciała, aby się ukrył, ale Lu-cien odmówił i odrywając od ściany obraz św. Franciszka, powiedział: „On mnie poprowadzi”.

Niebawem pojawili się bandyci, którzy postanowili go aresztować. Na ich widok Lucien powiedział bez wahania: „Jestem gotowy”. Poddał się bez najmniejszego oporu. Wiedział, że umrze. Kiedy go wezwali, wystąpił naprzód i powiedział donośnym głosem: „Wiem, że masz zamiar mnie zabić. Jeśli moje życie może ocalić innych, nie wahaj się mnie zabić. Jedyną rzeczą, o którą cię proszę, jest, abyś nie dotykał moich braci”. Około trzydziestu dawnych uczniów towarzyszyło mu do miejsca, gdzie odbywały się egzekucje. Szedł jak wolny człowiek, zwycięz-ca. Przed wykonaniem wyroku powiedział: „Powiedzcie mojej rodzinie, żeby nie płakała, bo jestem szczęśliwy. To Bóg zabiera mnie ze sobą. Niech wasze serca nigdy nie opuszczą Boga!”. Potem się modlił: „O mój Boże, wybacz moim braciom, którzy mają teraz trudne zadanie. Niech moja krew zostanie przelana za zbawienie mojej ojczyzny!”. Lucien powtórzył te słowa kilka razy. Potem bandyci chcieli związać mu ręce, ale odmówił. „Nie wiążcie mnie, aby mnie zabić. Sam się zwiążę”. I skrzyżował nadgarstki jeden na drugim, trzymając w ręku krzyż. Gdy padł na kolana, pomodlił się ponownie: „O mój Boże, przebacz moim braciom...”. Naj-pierw przebaczył oprawcom i wstawił się za nimi, podczas gdy oni szydzili z niego: „Twoja modlitwa jest zbyt długa! Czy myślisz, że to cię uratuje?”. Niektórzy z nich wykrzykiwali obelgi. Ale Lucien odpowiedział: „Jeszcze nie skończyłem! Zostaw mnie jeszcze chwilę!”. Podniósł ręce do nieba i trzykrotnie padł na ziemię, jak Jezus podczas Męki Pańskiej. Następnie zwrócił się do nich i powiedział: „Pospieszcie się, bo duch jest gotowy, ale ciało słabe”. Podczas gdy go zabijali, kaci szydzili z ofiary: „A teraz idź i zagraj na swojej fisharmonii”. Po śmierci jego ciało zostało wrzucone do rzeki Matitanana.

Uznając jego męczeństwo i świadectwo wiary, Kościół katolicki beatyfikował go 15 kwietnia 2018 r. Tym, co najbardziej charakteryzowało męczeństwo Luciena, była jego miłość do rodaków i prześladowców. Nieprzypadkowo został nazwany „Pojednawcą”.
`;