export const day5Postac = `
Simon Mpecke (1906-1975)

Simon urodził się w 1906 r. w Log Batombé w Kamerunie. Jako dziecko uczęszczał do szkoły podstawowej w misji katolickiej w Édéa. Była to misja otwarta przez pallotynów w okresie kolonii niemieckich. W wieku jedenastu lat uzyskał świadectwo ukończenia szkoły podstawowej. Rok później, 14 sierpnia 1918 r., w wieku dwunastu lat został ochrzczony. Dzień po chrzcie św. przystąpił do I Komunii św. Jako młody człowiek został nauczycielem w szkołach w Savannah, a wreszcie w misji centralnej w Édéa. W 1920 r. uzyskał dyplom nauczyciela.

W 1924 r. Simon wstąpił do małego seminarium w Yaoundé. Od października 1927 r. do grudnia 1935 r. studiował filozofię i teologię. Po ukończeniu studiów został jednym z pierwszych Kameruńczyków, którzy otrzymali święcenia kapłańskie. Stało się to 8 grudnia 1935 r. Te święcenia były kamieniem milowym w historii Kościoła w Kamerunie i zainaugurowały nową erę tego kraju.

W swojej pierwszej posłudze Simon został mianowany wikariuszem w misji Ngovayang, gdzie między innymi zajął zdecydowane stanowisko przeciwko brutalnym praktykom tradycyjnych religii. W 1947 r. został powołany do parafii w dzielnicy New-Bell w Douala, a rok później został jej proboszczem. Szybko nadał rozmach tejże wspólnocie. Wspierał Akcję Katolicką, bractwa i grupy. Troszczył się o działalność misyjnej szkoły. W tym samym czasie, przypadkowo przeczytał artykuł, z którego dowiedział się o istnieniu pogańskich plemion w północnym Kamerunie. Od tego momentu poczuł, jak rodzi się w nim wielkie współczucie i miłość do tych ludów.

W 1953 r. o. Mpecke wstąpił do Instytutu Świeckiego Braci Jezusa i wyjechał na roczny okres nowicjatu do Algierii. Był jednym z założycieli Unii Kapłańskiej „Jesus Caritas” i został jej pierwszym odpowiedzialnym w Kamerunie.

Prawdziwy przełom nastąpił jednak, kiedy papież Pius XII opublikował encyklikę Fidei Donum. W jej właśnie duchu o. Simon wyjechał do Kamerunu Północnego jako misjonarz. W tym okresie południe kraju, z większością ludów Bantu, przeszło już na chrześcijaństwo. Jednak północ, zamieszkana przez ludy pochodzenia sudańskiego, była lennem islamu. W lutym 1959 r., na prośbę miejscowego biskupa, ojciec Simon dotarł do Tokombéré, aby założyć misję i do-trzeć do ludu Kirdi, co w lokalnym narzeczu znaczy „poganie”. Początki misji katolickiej w Tokombéré były okazją do wyjątkowego doświadczenia misyjnego. Zadanie nie było łatwe: Simon Mpecke był w rzeczywistości postrzegany jako zagrożenie, ponieważ nie należał do miejscowego plemienia. Afrykański misjonarz szybko jednak rozwiał wszelkie oba-wy. Jego legendarna dobroć szybko przyniosła mu przydomek „Baba”, który oznacza ojca, patriarchę, mędrca czy przewodnika. Wszyscy: mężczyźni i kobiety, dorośli i dzieci, Kirdi i muzułmanie – spontanicznie zaczęli nazywać go „Ba-ba”, wyrażając tym samym swój szacunek i wdzięczność dla niego.

Od samego początku swej misyjnej pracy „Baba” po-stawił na edukację Kirdi. Szkoła była jego życiem i sposobem ewangelizacji. Edukacja bowiem przynosiła nadzieję na integralny rozwój miejscowych i pomagała w walce z wszechobecną ignorancją, tyranią i strachem. Była jego sposobem starania się o poszanowanie ludzkiej godności. W tym celu postanowił dać każdemu możliwość uczęszczania do „szkoły pod drzewem” – czyli do szkoły działającej na oczach wszystkich, w samym sercu codziennego życia Kirdi. Później dopiero zbudował szkołę Saint-Joseph w Tokombéré i uzyskał pozwolenie na otwarcie innych szkół. Poprzez szkoły, ośrodki zdrowia, zaangażowanie przeciwko niesprawiedliwości i codzienne wzywanie do powszechnego braterstwa umożliwił rzeczywistą poprawę warunków życia ludu Kirdi. Dzięki swojej działalności i przykładowi nauczył ludzi z tego plemienia kochać muzułmanów jak swoich braci. I co ciekawe, do takiej samej postawy przekonał muzułmanów. Jego troska o nieustanny dialog z przywódcami tradycyjnych religii uczyniła go także proroczym prekursorem dialogu międzyreligijnego. Na co dzień żył tak, jak Kirdi – ich ubóstwem i walką z nędzą. Jego codzienna ewangelizacja była przepojona modlitwą, miłością do Kościoła, miłosierdziem, przy jednoczesnym poszanowaniu lokalnych tradycji.

Jego wiara i przyjaźń z Jezusem utwierdzały go w przekonaniu, że tylko miłość uratuje miejscowych przed duchowym złem grzechu. Miłość pozwalała mu także chronić ukochanych parafian przed materialnym złem – nędzą, dyskryminacją etniczną i religijną.

W pewnym sensie, Baba Simon stał się podobny do Abrahama: jego exodus na północ Kamerunu i jego misja, umożliwiły narodziny nowego ludu. Zmarł 3 sierpnia 1975 r. Został pochowany w Tokombéré, pośród swojego ukochane-go ludu Kirdi.
`;