export const day6Postac = `
Bł. Pauline Marie Jaricot (1799-1862)

Pauline Marie Jaricot urodziła się w rodzinie pobożnych katolików, zaraz po rewolucji francuskiej, 22 lipca 1799 r. Była siódmą córką przemysłowców z Lyonu, miasta, którego chrześcijańskie korzenie sięgają II w. i które może poszczycić się Ojcem Kościoła św. Ireneuszem.

Pauline została ochrzczona w dniu swoich narodzin. Ze wszystkich relacji jasno wynika, że była radosnym i żywym dzieckiem, bardzo zdeterminowanym, a nawet upartym. W swojej autobiografii – którą należy czytać z ostrożnością, ponieważ Paulina była bardzo surowa wobec siebie – pisze: „Urodziłam się z żywą wyobraźnią, uporem, powierzchowną postawą, gwałtownym i leniwym charakterem. Byłabym całkowicie pochłonięta innymi rzeczami... [ale] Bóg dał mi lojalne serce, które łatwo oddawało się pobożności”. W okresie dorastania i wczesnej młodości była niekonsekwentna w swojej pobożności: na przemian przeżywała chwile intensywnej modlitwy przed Najświętszym Sakramentem czy też prosząc o wstawiennictwo Maryi Panny. Równocześnie, chętnie i z zaangażowaniem uczestniczyła w światowych wydarzeniach, gdzie nosiła eleganckie stroje, była podziwiana i adorowana przez młodych mężczyzn, z którymi fantazjowała o idyllicznych małżeństwach. Jej życie zmieniło się jednak drastycznie w wieku piętnastu lat, po wypadku w domu. Sprzątając, spadła bowiem ze stołka i gwałtownie uderzyła o ziemię. Upadek poważnie wpłynął na jej układ nerwowy, uniemożliwiając prawidłowe poruszanie kończynami i normalne mówienie. Chociaż lekarze próbowali różnych terapii, to jednak skutki były mizerne. Na dodatek, matka dziewczyny tak bardzo martwiła się o jej zdrowie, że również i ona zachorowała. Ojciec rodziny postanowił przenieść córkę do małej wioski na obrzeżach Lyonu, mając nadzieję, że rozdzielenie matki i córki pomoże im obu szybciej dojść do siebie. Miejscowy proboszcz zaprosił wówczas Pauline do wznowienia praktyk religijnych, a ona zdecydowała się poprosić o sakramenty pojednania i Eucharystii. Doświadczenie przebaczenia i duchowego pokrzepienia miało na nią głęboki wpływ.

Od tego momentu zaczęła powoli odzyskiwać zdrowie. Gdy była już w stanie chodzić, poszła do bazyliki Notre-Dame de Fourvière w Lyonie, aby modlić się przed wspaniałym wizerunkiem Matki Bożej ukazującej światu Dzieciątko Jezus. Od tego momentu Pauline postanowiła poświęcić swoje życie wyłącznie służbie ubogim i chorym. Wkrótce codziennie odwiedzała szpitale i nieuleczalnie chorych w domach, opatrując ich rany i niosąc słowa pocieszenia. Trosce o potrzebujących towarzyszyło intensywne życie modlitewne. Codziennie przyjmowała Eucharystię, modliła się o nawrócenie grzeszników i za ewangelizację. Wzrastało w niej nabożeństwo do Najświętszego Serca. To doświadczenie doprowadziło ją do utworzenia nowego stowarzyszenia o nazwie „Wynagrodzicielki”. Zaprosiła do niego wiele kobiet, które pracowały – niemal jak niewolnice – w miejskich fabrykach jedwabiu. Jej medytacje przed tabernakulum zainspirowały ją także do napisania i opublikowania książki o nieskończonej miłości w Boskiej Eucharystii, która stała się źródłem pocieszenia i duchowego pokarmu dla wielu z tychże kobiet.

W tym czasie jej brat Phileas kształcił się w seminarium duchownym w Paryżu. To on poinformował Paulinę o swoich misyjnych planach i o potrzebie znalezienia środków, aby wysyłać misjonarzy do Azji. Wtedy to Pauline wpadła na pomysł, który zmienił historię współpracy misyjnej: poprosiła członkinie swojego stowarzyszenia, aby każda znalazła dziesięć nowych osób, które będą się modlić i ofiarują jednego centa tygodniowo na ewangelizację świata lub – jak mówiono w czasach Pauliny – na szerzenie wiary. Dla każdych dziesięciu nowych członków ustanawiała przywódcę, podob-nie czyniąc dla każdej setki i tysiąca. Pomysł był prosty: modlić się i zbierać fundusze, tworząc sieć osobistych relacji. Lider grupy dziesięciu spotykał się z członkami i zbierał grosze co tydzień, lider grupy stu zbierał je od liderów dziesięciu, a lider grupy tysiąca od liderów setek. Zebrane i – jak na tamtejsze warunki – znaczne fundusze, byłyby dzielone i wysyłane na cały świat.

Pomysł rozprzestrzenił się i z czasem powstało Dzieło Rozkrzewiania Wiary. 22 maja 1922 r., decyzją papieża Piusa XI, zostało ono uznane za papieskie. W ten sposób ojciec święty chciał wyrazić swoją ojcowską troskę wobec Kościołów lokalnych, które powstały w wyniku działalności misyjnej. Aktywność Pauline i jej sława jako pobożnej i zdecydowanej kobiety wiary zyskała jej wielki szacunek ze strony ojca świętego. Pauline też wspierała radą kardynałów, biskupów i świętych jej współczesnych.

Warto przypomnieć także jeszcze inną jej inicjatywę. W 1826 r., zachęcona sukcesem swego dzieła misyjnego tworzonego przez małe grupy, Paulinę zastosowała to samo kryterium, inicjując i proponując Żywy Różaniec. Zaczęła organizować swoich przyjaciół i współpracowników w grupy piętnastu osób, odpowiednio do ówczesnej liczby tajemnic różańcowych. Każdego członka prosiła, aby zobowiązał się do codziennego odmawiania jednej dziesiątki różańca i rozważania jednej tajemnicy dziennie przez okres całego miesiąca. W ten sposób codziennie odmawiano cały różaniec i rozważano wszystkie piętnaście tajemnic. Na początku miesiąca lider grupy osobiście rozdzielał tajemnice między członków, upewniając się, że każdy otrzymał inną tajemnicę do medytacji. Marzenie Pauliny o Żywym Różańcu wkrótce stało się fenomenem na skalę światową. W 1831 r. napisała: „15-osobowe grupy nadal mnożą się z niewiarygodną szybkością we Włoszech, Szwajcarii, Belgii, Anglii i w różnych częściach Ameryki. Różaniec rozprzestrzenił swoje korzenie aż do Indii, a zwłaszcza w Kanadzie”. Pauline miała nadzieję, że Żywy Różaniec zjednoczy ludzi rozproszonych po całym świecie w żarliwej modlitwie za misję Kościoła. Inicjatywa Żywego Różańca odniosła tak wielki sukces, że po śmierci Pauline istniało ponad 150 000 grup, zrzeszających 2 250 000 członków w samej Francji!

Pod koniec życia zdrowie Pauline zaczęło się pogarszać. Zdecydowała się wtedy na pielgrzymkę do Rzymu, ale tam poczuła się jeszcze gorzej. Podczas gdy była przykuta do łóżka, sam ojciec święty odwiedził ją i pobłogosławił. Zmarła spokojnie 9 stycznia 1862 r. Została beatyfikowana 22 maja 2022 r.
`;