export const day7Postac = `
Vivian Uchechi Ogu (1995-2009)

Vivian Uchechi Ogu urodziła się 1 kwietnia 1995 r. w Benin City w Nigerii. Podczas nauki w szkole podstawowej wyróżniała się jako jedna z najlepszych uczennic. Z tego też powodu reprezentowała swoją szkołę w wielu konkursach, zwłaszcza matematycznych. Marzyła, aby zostać prawnikiem i bronić praw biednych i uciśnionych, zwłaszcza wdów i sierot. Chciała także zostać inżynierem lotnictwa, aby udowodnić, że zawód ten nie jest tylko dla mężczyzn. Jej hobby było: czytanie, śpiew i taniec.

W toku zajęć pozalekcyjnych Vivian dołączyła do grupy międzywyznaniowej, gdzie pełniła funkcję asystenta lidera modlitwy. W ramach niedzielnych spo-tkań katechizmowych, mając zaledwie dziewięć lat, publicz-nie demonstrowała swoją gorliwość i odwagę w rozmowach o przyjaźni z Jezusem, o wierze, o godności czystości i dzie-wictwa. Zawsze była gotowa, aby pomóc kolegom, udzielając rad i dzieląc się doświadczeniem chrześcijańskiego życia. Dzięki Katolickiej Odnowie Charyzmatycznej, którą poznała za sprawą swoich rodziców, doświadczyła duchowego przebudzenia. Mimo młodego wieku była bardzo zaangażowana. Brała udział kursach biblijnych. Uczestniczyła niemal we wszystkich specjalnych wydarzeniach organizowanych przy kościele, takich jak choćby Dzień Dziecka czy Święta Dziękczynienia. Biorąc udział w spotkaniach chóru, zauważyła, że prowadząca go osoba nie jest zbytnio sumienna. Postanowiła więc zaangażować się. Tak bardzo chciała zorganizować zdolny i zdyscyplinowany chór, że z pomocą ojca opracowała nawet jego statut. Propozycja została zatwierdzona przez przełożonego animatorów parafialnych i tak narodził się pierwszy statut parafialnego chóru dziecięcego. Przez następne cztery lata, pod kierownictwem Vivian, chór rozrósł się z małej grupy około 20 dzieci do prawie 60. Chór ten bardzo często zajmował pierwsze miejsce w różnych konkursach muzycznych. Vivian, mimo młodego wieku, doskonale rozumiała ideę umartwienia i poświęcenia. Zachęcała więc inne dzieci do podjęcia umartwienia w intencji zbawienia, osobistego nawrócenia, czy też w intencji najbardziej potrzebujących dzieci w parafii i na świecie. Nic więc dziwnego, że kiedy zainaugurowano w parafii Papieskie Dzieło Misyjne Dzieci została jednogłośnie wybrana na jego pierwszą przewodniczącą. Podczas swojej kadencji pracowała niestrudze-nie. Wśród projektów, które koordynowała z zapałem i pomysłowością znalazły się między innymi: zbiórka funduszy na pokrycie kosztów leczenia niektórych niepełnosprawnych dzieci w Centralnym Szpitalu w Benin City, czy zaspokojenie potrzeb dzieci w sierocińcach w Edo i Oronsaye.

W 2009 r., w związku z Dniem Dziecka, Vivian zmobilizowała całą parafię do utworzenia funduszu solidarnościowego dla biedniejszych parafian. Dziewczynka uwielbiała czytać Pismo Święte i często prosiła swoich księży i animatorów o wyjaśnienie poszczególnych kwestii biblijnych. Poruszona swoją miłością do Słowa Bożego, postanowiła także poświęcić się spisywa-niu swojego rozumienia Ewangelii według św. Mateusza. Dzięki pracy w PDMD Vivian poznała historię św. Marii Goretti, która stała się jej ulubioną świętą. W tym kontekście często zapraszała swoich rówieśników do życia w czystej przyjaźni z Jezusem i pouczała ich o wartości dziewictwa. Wraz ze swoją heroiczną śmiercią, Vivian dała konkretny przykład tego nauczania, które kontynuowała aż do poranka swojego męczeństwa.

W niedzielę, 15 listopada 2009 r., do domu jej rodziny wtargnęli uzbrojeni bandyci. Okradli dom, a następnie zabrali Vivian i jej siostrę poza miasto, obok rządowego obszaru przemysłowego. Złodzieje próbowali tam ją zgwałcić, ale stanowczo się broniła. Ostatecznie została przez nich zastrzelona. Po Mszy św. pogrzebowej jej ciało zostało przewiezione do jej rodzinnego miasta Aboh Mbaise i tam pochowane. Dowiedziawszy się o bohaterskiej śmierci dziewczyny, władze samorządowe przyznały ten teren archidiecezji Benin City. Dwa lata później miejscowy samorząd nadał nazwę „Vivian Ogu” ulicy, na której zginęła. Począwszy od 2010 r., wierni archidiecezji gromadzą się w miejscu jej śmierci każdego 15 listopada. W dniu 29 marca 2014 r. pasterz archidiecezji Benin City, zainaugurował Ruch Vivian Ogu, którego zadaniem jest rozpowszechnianie historii męczeńnicy. Jednocześnie zbierane są świadectwa o jej heroicznym życiu i łaskach uzyskanych za jej wstawiennictwem.
`;