export const day8Postac = `
Bł. Peter To Rot (1912-1945)

W 1882 r. pierwsza grupa misjonarzy Najświętszego Serca Jezusowego ewangelizujących dzisiejszą Papuę Nową Gwineę dotarła do wioski Rakunai. Wkrótce, ku ich zaskoczeniu i radości, wódz wioski, Angelo Puia, ogłosił, że on i większość mieszkańców chcą zostać katolikami. To właśnie w rodzinie tegoż wodza w 1912 r. przyszedł na świat Peter. Rodzina była bardzo religijna. Ojciec pilnował, aby wszyscy zostali ochrzczeni i przekazywał im podstawowe prawdy katechizmu, podczas gdy matka uczyła ich modlitwy. Jako dziecko, Peter podjął naukę w szkole misyjnej. Okazał się być wyjątkowym i pracowitym uczniem. Chłopiec miał przy tym szczególnie żywy temperament, był troskliwy i pomocny. Przykładowo wspinał się na palmy, by zbierać orzechy kokosowe i ofiarować je starszym mieszkańcom wioski, mimo że jako syn wielkiego wodza, mógł oczekiwać, by to inni przyszli im z pomocą.

W 1930 r. proboszcz miejscowej parafii zasugerował ojcu Petera, że jego młodzi synowie mogliby przygotowywać się do kapłaństwa. Puia odpowiedział jednak: „Myślę, że nie nadszedł jeszcze czas, aby jeden z moich synów lub inny mężczyzna z tej wioski został księdzem. Ale jeśli chcesz wysłać go do szkoły katechetycznej w Taliligap, to się zgadzam”. Wkrótce po tej rozmowie Peter z radością rozpoczął przygotowanie do pracy katechisty w Kolegium św. Pawła. Dzieląc czas na naukę i ćwiczenia duchowe, pracował także fizycznie w szkolnym gospodarstwie rolnym. W tym okresie dał się też poznać jako radosny towarzysz i człowiek pojednania. W 1934 r. Peter To Rot otrzymał od biskupa krzyż katechetyczny i został odesłany do swojej rodzinnej wioski, aby tam pomagać w pracy ewangelizacyjnej. Nie szczędził sił: katechizował dzieci, formował dorosłych, przewodniczył spotkaniom modlitewnym, przygotowywał liturgię niedzielnych mszy św., pomagał przygotować się do spowiedzi św. Ponadto gorliwie zwalczał czary, które były praktykowane przez wielu, nawet przez katolików. W 1936 r. Peter poślubił Paulę Ia Varpit, młodą kobietę z sąsiedniej wioski. Zbudowali przykładne, chrześcijańskie małżeństwo, przepełnione miłością i szacunkiem.

Życie Petera i jego rodziny zmieniło się w 1942 r. Wtedy to, podczas trwającej II wojny światowej Japończycy najechali Nową Gwineę i bardzo szybko umieścili większość księży i zakonników w obozach koncentracyjnych. Będąc osobą świecką, Peter mógł pozostać w swojej wiosce, ale musiał podjąć nowe zadania. Animował liturgię, chrzcił, przewodniczył pogrzebom. Od ukrywającego się kapłana przynosił Komunię św. i rozdawał ją wiernym. W lesie zbudował z gałęzi kaplicę, gdzie przechowywał naczynia liturgiczne. Gdy Japończycy zwrócili się także przeciwko katolikom świeckim, naciskając na nich, by porzucili wiarę i wrócili do poligamii, Peter zaprotestował. Przeciwstawił się nawet swojemu bratu Josephowi. Wtedy też po raz pierwszy został zatrzymany.

Widząc determinację męża, żona Petera coraz bardziej obawiała się, że zagrozi to ich rodzinie. Usłyszała wówczas: „Jeśli będę musiał umrzeć, to umrę za Królestwo Boże w naszym narodzie”. W tym czasie Japończycy, kontynuując swoją politykę, wydali zakaz celebracji liturgicznych. Pomimo to, Peter po opuszczeniu więzienia nadal działał w ukryciu jako katechista. Na skutek donosu został jednak zatrzymany i trafił do obozu koncentracyjnego. Podczas przesłuchania przyznał, że dzień wcześniej prowadził spotkanie modlitewne. Wyznał także swój sprzeciw wobec bigamii. Jak później powiedział odwiedzającej go rodzinie, „dla szefa policji była to moja główna zbrodnia”. Więzień był przetrzymywany w małej celi bez okien. Chociaż był traktowany gorzej niż inni więźniowie – do końca pozostał pogodny. Został zabity przez japońskiego lekarza, który 7 lipca 1945 r. podał mu zastrzyk z trucizną. Peter To Rot został pochowany na cmentarzu w Rakunai, a jego grób stał się szyb-ko miejscem pielgrzymek. Podczas swojej wizyty duszpasterskiej w Oceanii w 1995 r. papież Jan Paweł II beatyfikował Petera To Rot. Opisując jego życie i śmierć, mówił: Skazany bez procesu, spokojnie znosił swoje męczeństwo.

Podążając śladami swego Mistrza, „Baranka Bożego, który gładzi grze-chy świata” (J 1,29), on również był „prowadzony jak baranek na rzeź”. Niemniej jednak to „ziarno pszenicy”, które po cichu wpadło w ziemię (por. J 12,24), przyniosło plon w postaci żniwa błogosławieństw dla Kościoła w Papui Nowej Gwinei! Dzięki Duchowi Bożemu, który w nim mieszkał, odważnie głosił prawdę o świętości małżeństwa.
`;