export const day9Postac = `
Mon Filomena Yamamoto (1930-2014)

Mon Filomena Yamamoto, Japonka, opuściła tę ziemię 28 kwietnia 2014 r. Miała wtedy 83 lata. Dziesięć lat wcześniej opowiedziała w czasopiśmie „Xaverian” o swoim spotkaniu z Chrystusem: „Myśląc o środowisku, w którym dorastałam i o wydarzeniach, które poprzedziły łaskę chrztu św., wyraźnie widzę kochającą rękę Boga, która prowadziła mnie w cichy i ukryty sposób. Urodziłam się w buddyjskiej rodzinie zen. W domu był mały ołtarzyk, na którym znajdowały się tabliczki naszych przodków. Każdego ranka ofiarowywaliśmy filiżankę herbaty i filiżankę ryżu i zatrzymywaliśmy się, by pomodlić się ze złożonymi rękami. Kiedy czasem obok naszego domu przechodzili pielgrzymi w drodze do jakiejś świątyni lub biedni ludzie, zawsze oferowaliśmy im ryż. Mieliśmy głęboki związek ze świątynią. Jako dziecko często ją odwiedzałam i słuchałam kazań. Zastanawiałam się, dlaczego człowiek się rodzi, a potem umiera? Dlaczego istnieje cierpienie? Jak to się dzieje, że na świecie ci, którzy czynią dobro, często cierpią, podczas gdy ci, którzy czynią zło, odnoszą sukcesy i żyją w komforcie? Nie miałam przy tym odwagi zapytać dorosłych, ponieważ miałam wrażenie, że nie będą w stanie mi odpowiedzieć.

Podziwiając naturę z cudownym spektaklem zmieniających się pór roku, czułam, że Pan przemawia do mnie. Czułam, że oprócz bóstw starożytnych religii Japonii, musi istnieć Bóg stwórca nieba i ziemi. Wiedziałam, że muszę szukać prawdziwej religii. Modliłam się, aby ją odkryć, ale nie wiedziałam, gdzie ją znaleźć. Kiedy miałam 23 lata, wyjechałam z rodzinnego miasta do Miyazaki. Zaproszona przez przyjaciela, zaczęłam uczęszczać do kościoła katolickiego i na katechezę. Na początku miałam pewne opory przed wiarą w jednego Boga, ponieważ japońska kultura jest przesiąknięta obecnością licznych bóstw, które się nie wykluczają. Mimo to kontynuowałam zgłębianie chrześcijaństwa. Po pewnym czasie, słuchając opisu męki i zmartwychwstania Pana Jezusa, zaczęłam rozumieć cudowność dzieła odkupienia. Poczułam, że w końcu znalazłam to, czego szukałam przez lata”.

Od najwcześniejszej młodości Mon pragnęła życia całkowicie poświęconego innym. Jeszcze jako katechumenka była także zafascynowana ideą poświęcenia całego swojego życia Bożemu miłosierdziu. Wzorem była dla niej św. Teresa z Lisieux. W tym duchu Mon wstąpiła do Zgromadzenia Misjonarek Maryi. Jedna z sióstr z tamtego okresu, wspomina: „Mon była siostrą wierną swojemu życiowemu wyborowi. Tworzyła harmonię w każdej wspólnocie, do której przeznaczało ją posłuszeństwo. Jej pogoda ducha, humor i prostota sprawiały, że każda siostra czuła się cudownie. Była prawdziwą, ewangeliczną osobą, jedną z tych, do których należy Królestwo Niebieskie. Żyła chwilą obecną, wszystko przeżywając z Jezusem. „Otwarta, umiała radzić sobie z nowymi i nieoczekiwanymi sytuacjami” – dodaje inna siostra. „Zawsze była na bieżąco ze światowymi i krajowymi problemami, aby przedstawiać je potem na modlitwie i dzielić się nimi z ludźmi, których spotykała”. Lubiła odwiedzać chorych, starszych, samotnych. Pewien misjonarz wspomina: „Z nią nauczyłem się, jak podchodzić do chorych, jak modlić się razem z nimi, jak ich pocieszać i jak wprowadzać Jezusa w ich życie. Mon otworzyła mi drogę do bycia prawdziwym misjonarzem. Była bardzo wrażliwa na fizyczne cierpienie innych, a jej spojrzenie przenikało do najgłębszych zakamarków serc. Pragnęła przygotować każdego na przyjęcie zbawczego dzieła Boskiego Lekarza”.

W 2011 r. zdiagnozowano u niej raka. „Odwiedziłem ją w szpitalu – pisze znajomy misjonarz ksawerianin. – Uczyniła ze swojego pokoju «mały kościół», w którym przebywała w towarzystwie Jezusa. Podczas chemioterapii spokojnie przygotowywała się na śmierć i rozmawiała o tym z tymi, którzy przychodzili ją odwiedzić. Dawała świadectwo wiary i pogody ducha, które płynęły z jej bezwarunkowego zaufania do Jezusa. Miała zawsze słowa podziękowania dla wszystkich. Podczas kolejnych hospitalizacji jej spokój imponował. Wielu widząc ją uśmiechniętą, zastanawiało się, czy naprawdę jest chora. W swoich ostatnich dniach modliła się nieustannie: „Panie, przyjdź wkrótce, aby mnie zabrać”. Odeszła w wielkim pokoju...

Patrząc na jej życie, warto przywołać słowa papieża Franciszka: „Każdy święty jest misją; jest planem Ojca, by odzwierciedlać, ucieleśniać w danym momencie dziejów, pewien aspekt Ewangelii. Misja ta znajduje pełny sens w Chrystusie i można ją zrozumieć jedynie rozpoczynając od Niego. W swej istocie świętość, to przeżywanie w zjednoczeniu z Nim tajemnic swojego życia” (Franciszek, Gaudete et exsultate, nr 19-20).
`;