export const day1study = `
Tegoroczne rekolekcje pielgrzymkowe przeżywamy pod hasłem: „Żyję w Kościele”. Można by pomyśleć, że staramy się przeanalizować różne wymiary działalności Kościoła. W rzeczywistości chodzi nam jednak o coś więcej. Chcemy lepiej poznać tę wspólnotę, do której zostaliśmy włączeni przez chrzest św. Chcemy na nowo się nią zafascynować. Bo jak nie zachwycić się tym, że właśnie w Kościele i przez Kościół sam Jezus obdarza nas swoją miłosierną miłością?

Warto w tym momencie uświadomić sobie, jak wielkim darem jest Kościół. Pomyśl, bracie i siostro, jak wyglądałoby Twoje życie bez tych wszystkich łask, bez miłosierdzia, które Jezus ofiarował Ci i ciągle ofiarowuje w Kościele? Jaka byłaby Twoja droga do zbawienia?

Skoro żyję w Kościele, to wypada dobrze go znać. Czy pamiętam, jak Kościół powstawał? Niejako dając odpowiedź na to pytanie, papież Franciszek mówił: „W sposób (…) szczególny Bóg otacza czułą miłością Kościół. Zaczął się on w sercu Boga Ojca. Gdy Bóg powołał Abrahama, powziął zamysł, aby utworzyć lud pobłogosławiony Jego miłością, który poniesie Jego błogosławieństwo wszystkim narodom. Projekt ten znalazł swe wypełnienie w Jezusie Chrystusie, który wezwał swoich uczniów do trwania w Jego miłości. Dzięki mocy Ducha Świętego ta wspólnota miłości trwa i nieustannie realizuje się w Kościele”.

Ten projekt, ten Boży zamysł dokonywał się etapami: powołanie uczniów (Łk 5,10-11), wybór apostołów (Łk 6,12-16), ustanowienie sakramentów (np. pokuty: J 20,22-23), przykazania miłości (Mt 22,36-40), nadanie prymatu św. Piotrowi (Mt 16,18-19). Wreszcie męka, śmierć i zmartwychwstanie oraz zesłanie Ducha Świętego (Dz 2,1-13).

Moi drodzy! Właśnie tak „rodziła się” i powstała ta wspólnota wiary, w której żyjemy. I to, co jest najważniejsze i fascynujące: Jezus, od momentu, kiedy ustanowił Kościół, nadal w nim działa przez Ducha Świętego. Ojciec święty Franciszek oddaje tę prawdę następująco: „Bóg napełnia nas swoim miłosierdziem i miłością, a to sprawia, że wzrastamy jako Lud Boży, jako Kościół. Być Kościołem, to znaczy czuć, że jesteśmy w rękach Boga, który nas kocha, czeka na nas i daje nam odczuć swą czułość”.

Bracie i siostro! Czyż to nie fascynujące? Wyobraź sobie otwartą dłoń Boga, na której leży maleńkie ziarenko, którym jesteś Ty sam. Bóg wpatruje się w Ciebie z miłością, przygląda Ci się i całuje. Przez swego Ducha obdarza Cię swoim miłosierdziem, abyś wzrastał, abyś zakwitł. To jest właśnie Kościół. To jest Kościół, który tworzymy i w którym żyjemy.

Chciałbym teraz podzielić się z Wami pewnym wspomnieniem. Odwiedzając kiedyś polskich misjonarzy pracujących w brazylijskiej Amazonii, przeżyłem ciekawe doświadczenie. Otóż, pewnego dnia popłynęliśmy do jednej z maleńkich wspólnot. Aby dotrzeć do tych ludzi, płynęliśmy łodzią motorową przez dobrych kilka godzin. Podczas drogi dowiedziałem się, że misjonarz – nasz przewodnik – odwiedza ich zaledwie kilka razy w roku. Kiedy wreszcie dotarliśmy, zostaliśmy najpierw bardzo serdecznie przywitani, a potem miała miejsce spowiedź św. Później, w bardzo poniszczonej, drewnianej kaplicy sprawowaliśmy Mszę św. Po jej zakończeniu lider tej kilkunastoosobowej wspólnoty poprosił, abyśmy poszli na drugi koniec wioski, gdzie naszym oczom ukazał się zaskakujący widok: tamci ludzie sami wybudowali nową, murowaną kaplicę, w której chcą się gromadzić jako wspólnota nawet wówczas, kiedy nie będzie z nimi duszpasterza… Chyba tylko oni wiedzieli, ile ryb musieli złowić i sprzedać, żeby zdobyć pieniądze i wykonać to dzieło.

Dlaczego o tym mówię? W Kościele jesteśmy braćmi i siostrami, a tę „rodzinę” mamy na całym świecie. Poza tym jesteśmy w Kościele prawdziwą wspólnotą. Ale nie dzięki naszym wysiłkom. Św. Paweł Apostoł pisze w Liście do Rzymian: „Albowiem wszyscy ci, których prowadzi Duch Boży, są synami Bożymi. Nie otrzymaliście przecież ducha niewoli, by się znowu pogrążyć w bojaźni, ale otrzymaliście ducha przybrania za synów, w którym możemy wołać: «Abba, Ojcze!». Sam Duch wspiera swym świadectwem naszego ducha, że jesteśmy dziećmi Bożymi” (Rz 8,14-16).

W kontekście tych słów trzeba to sobie uświadomić. W Kościele Duch Święty tworzy wspólnotę człowieka z Bogiem i wspólnotę między nami! On to czyni! Czyż to nie wspaniałe!

Ciekawie opisuje to papież Franciszek, mówiąc: „Kościół matką! Nie jest on ani organizacją pozarządową, ani koncernem, ale historią miłości. Każdy wierzący jest ogniwem tego łańcucha miłości, która nie wzrasta dzięki ludzkiej sile, ale mocą Ducha Świętego. Dzięki Niemu wszyscy razem jesteśmy jedną rodziną w Kościele, który jest naszą matką”.

Piękne określenie: Kościół – matką. Ale czy ja tę matkę kocham i czy jestem jej posłuszny? Przecież w niej troszczy się o mnie sam Jezus Zmartwychwstały! Jeśli twierdzę, że wierzę, ale moje poglądy są inne, niż uczy Kościół, to do kogo się odwracam plecami? Do kochającej matki i do miłującego mnie po krzyż miłosiernego Zbawiciela! I z pewnością to nie Kościół – moja matka – najwięcej na tym traci…

Moi drodzy, Kościół to nie punkt usługowy czy inna instytucja. To wspólnota, to my – kroczący przez życie z Panem, to Lud Boży, który działa w nas przez swego Ducha. I o tym mamy świadczyć naszym życiem i tę Dobrą Nowinę zanieść do każdego człowieka – tego blisko i tego daleko, choćby tam, w Amazonii. Jezus mówi bowiem do nas: „gdy Duch Święty zstąpi na was, otrzymacie Jego moc i będziecie moimi świadkami w Jerozolimie i w całej Judei, i w Samarii, i aż po krańce ziemi” (Dz 1,8).

Na koniec przytoczę słowa papieża – jego radę, jaką daje nam, mówiąc o Kościele, a właściwie o tym, co jest w nim ludzką słabością: „Tylko miłość czyni nas zdolnymi do pełnego wyrażenia prawdy (…), do wskazywania tego, co szwankuje, ale także do uznania całego dobra i świętości, które są obecne w Kościele, począwszy właśnie od Jezusa i Maryi. Miłować Kościół, chronić Kościół i wraz z nim iść. Kościół to nie jest grupka ludzi wokół księdza, która wszystkimi rządzi. Kościołem jesteśmy my wszyscy. W drodze. Chronić jeden drugiego, chronić się nawzajem. Mam pytanie: czy kiedy mamy z kimś problem, to go chronimy, czy od razu potępiamy, niszczymy. Strzec. Chronić. Zachęcam was, abyście prosili o wstawiennictwo św. Józefa właśnie w najtrudniejszych chwilach waszego życia i życia waszych wspólnot. Gdy nasze błędy stają się skandalem, prośmy św. Józefa, aby dał nam odwagę mówienia prawdy, proszenia o przebaczenie i pokornego zaczynania od nowa”.
`;