export const day2Study = `
Kościół karmi mnie Słowem

Dzisiejszą refleksję chciałbym znów rozpocząć od misyjnego wspomnienia. Otóż, kiedy odwiedzałem siostry misjonarki w Burundi, wiele usłyszałem o lokalnych konfliktach plemiennych. Siostry wspominały zwłaszcza o krwawych walkach między dwoma spośród nich. I chociaż historie te pełne były przemocy, to jednak jedna z nich była bardzo pozytywna, a nawet wzruszająca. Mianowicie, w czasie lokalnego konfliktu szpital prowadzony przez siostry otoczyli bojownicy jednego z plemion. Przebywały w nim między innymi chore dzieci z obu zwaśnionych klanów i czuwające przy nich matki. Któregoś dnia, do jednej z nich dostał się mąż, przynosząc trochę żywności, a konkretnie – manioku. Ponieważ w tym okresie brakowało jedzenia, kobieta zaraz nakarmiła swoje dziecko i podzieliła się z jeszcze jedną matką ze swego plemienia. Po chwili jednak wstała i poszła na drugi koniec sali, gdzie przebywała matka ze zwaśnionego plemienia. Jej też podała część manioku. Mimo krwawego konfliktu trwającego za murami szpitala, matka zrozumiała matkę zmartwioną chorym i głod-nym dzieckiem…

Dlaczego o tym wspominam? Mówiliśmy wczoraj, że Kościół jest matką. A jako kochająca nas matka, troszczy się o nas i karmi nas – Słowem i Ciałem Pana. Widać to najlepiej w historii uczniów idących do Emaus (Łk 24,13-35). Zmartwychwstały Jezus najpierw wyjaśniał im pisma, a potem połamał dla nich chleb. To czyni nadal w Kościele, kiedy przychodzi do nas w swoim Słowie. „Oto stoję u drzwi i kołaczę: jeśli kto posłyszy mój głos i drzwi otworzy, wejdę do niego i będę z nim wieczerzał, a on ze Mną” (Ap 3,20). Jeśli posłyszy… Właśnie. Czy staramy się to Słowo usłyszeć?

W Czadzie, podczas liturgii w jednej z wiosek widziałem, jak wierni podczas czytania Ewangelii siadali. Byłem zaskoczony, bo w Polsce przecież stoimy. Dowiedziałem się potem, że to nawiązanie do lokalnej tradycji – kiedy bowiem przemawia szef wioski, trzeba usiąść na znak szacunku i… aby słuchać uważniej. Czyż nie takie nastawienie powinno nas charakteryzować podczas słuchania Bożego Słowa? Przypomina o tym także Maryja, mówiąc w mistycznej wizji do Cataliny Rivas: „Chcę, żebyś uważnie słuchała czytań i homilii kapłana. Pamiętaj, że Pismo Święte mówi, iż Słowo Boże nie powraca, nie wydawszy owocu. Jeśli będziesz uważna, zostanie w tobie coś z tego, co usłyszysz. Próbuj pamiętać przez cały dzień te słowa, które zostawiają w tobie jakiś ślad. Raz mogą to być dwa zdania, innym razem cały fragment Ewangelii, kiedy indziej będziesz smakować przez resztę dnia zaledwie jedno słowo, które stanie się częścią ciebie. Twoje życie zmieni się, jeśli pozwolisz słowu Bożemu przemieniać cię”. Pomijając, że czasem, z obiektywnych powodów nie możemy się skupić, ktoś może powiedzieć: „Tak, ale te teksty, zwłaszcza z Ewangelii, ja już dobrze znam”. Może i tak. Ale Pan znów chce Ci coś powiedzieć. I to z miłości do Ciebie… Przecież od momentu, kiedy słuchałeś ostatni raz tego fragmentu, tak dużo wydarzyło się w Tobie i wokół Ciebie, w Twoim życiu.

Pięknie pisze o tym św. Efrem: „Któż jest zdolny, aby pojąć, o Panie, wszystkie bogactwa jednego tylko z Twoich słów? Jest o wiele więcej tego, co nam umyka, od tego, co udaje nam się pojąć. Jesteśmy jak spragnieni, którzy piją ze źródła. Twoje słowo ma wiele różnych aspektów, tak jak liczne są perspektywy tych, którzy je badają”. W tym kontekście przytoczę też ostrzeżenie papieża Franciszka: „Dlatego konieczne jest, aby nigdy nie przyzwyczajać się do Słowa Bożego, ale karmić się Nim, by coraz głębiej odkrywać i przeżywać naszą relację z Bogiem i braćmi. (…).

Słowo Boże nieustannie przypomina nam o miłosiernej miłości Ojca, który prosi swoje dzieci, aby żyły w miłości. Życie Jezusa jest pełnym i doskonałym wyrazem tej Boskiej miłości, która niczego nie zatrzymuje dla siebie, ale ofiarowuje się każdemu bezgranicznie”.

Podzielę się teraz z Wami pewnym pielgrzymkowym spostrzeżeniem. I wcale nie chodzi o to, że na pielgrzymce, z wielu powodów, trzeba naprawdę się wysilić, aby słuchać Pana. Bo zmęczenie, bo deszcz, bo słabo słychać… i tak dalej. Chodzi natomiast o to, że dawniej dla pielgrzyma było radością, że śpi w domu, a nie w stodole z dziurawym da-chem. A teraz – jego radością jest fakt, że ma naładowany telefon komórkowy. Pomyślmy zatem: ile razy dziennie „zaglądam” do telefonu, czytam SMS-y, przeglądam strony internetowe? A czy mam w nim zainstalowane Pismo Święte? Może warto …bo przecież – jak mówi św. Paweł do Tymoteusza: „Wszelkie Pismo od Boga natchnione [jest] i pożyteczne do nauczania, do przekonywania, do poprawiania, do kształcenia w sprawiedliwości – by człowiek Boży był doskonały, przysposobiony do każdego dobrego czynu” (2 Tm 3,16). Bracia i siostry, pielgrzymi! Nie kto inny, ale sam Jezus chce nas karmić. Pozwólmy Mu. Może sięganie po Biblię lub aplikację z nią stanie się naszym codziennym popielgrzymkowym zwyczajem? Przecież żyjemy w Kościele, a możemy dzięki Bożemu Słowu żyć pełniej i piękniej. 

Jest taka cenna wrześniowa inicjatywa, która nazywa się „Narodowe Czytanie”. Proponuję ją przejąć i nieco zmodyfikować: „Codzienne Biblijne Czytanie”. I nie szukaj wymówki, że nie masz czasu, bo wiesz, że jest inaczej – wystarczy odrobina dobrej woli i nieco wymagania od siebie. I na koniec jeszcze jedna fundamentalna prawda. Co, a właściwie kto jest potrzebny, aby rozsmakować się w Bo-żym Słowie? Jako odpowiedź przytoczę świadectwo pewnego człowieka: „Jerzy regularnie czyta Pismo Święte od ponad 35 lat. «Najpierw myślałem, że chodzi głównie o czytanie Biblii, a potem dopiero zrozumiałem, że chodzi bardziej o słuchanie – o to, by usłyszeć żywego Boga, który do nas mówi» – tłumaczy. Dodaje, że momentem przełomowym było dla niego także uświadomienie sobie, że warto przed każdym czytaniem modlić się do Ducha Świętego. Mówił: «Wiemy, że to Duch podyktował kiedyś słowo Boże tym, którzy je spisali… Skoro On je – że tak powiem – zakodował, to On jest potrzebny, by je odkodować dla każdego, kto je czyta». Wspomina, że właśnie wsłuchiwanie się w słowo poprzedzone modlitwą do Ducha Świętego otwarło przed nim Biblię w nowy sposób. Pewne słowa zaczęły go poruszać, dotykać. Kiedy pod ich wpływem podejmował konkretne decyzje w swoim życiu, były to zawsze decyzje dobre. Słowo wnosi w jego codzienność pokój”.

Po wysłuchaniu tego świadectwa chyba wiemy już, Kogo potrzebujemy… Zakończmy zatem, przywołując raz jeszcze pouczenia ojca świętego: „Jako chrześcijanie jesteśmy jednym ludem kroczącym w historii, jesteśmy silni obecnością Pana pośród nas, który do nas przemawia i nas karmi. Dzień poświęcony Biblii nie powinien być raz w roku, ale w każdym dniu roku, ponieważ musimy pilnie stać się bliscy Pismu Świętemu oraz Zmartwychwstałemu, który nigdy nie przestaje dzielić się Słowem i Chlebem we wspólnocie wierzących. W tym celu musimy wejść w bliską relację z Pismem Świętym, w przeciwnym razie nasze serce pozostanie zimne, a oczy zamknięte, dotknięte niezliczonymi formami ślepoty”.
`;