export const day3study = `
Misja Kościoła

Czy pamiętacie z naszej pierwszej refleksji, jakie zadanie ma Kościół – czyli my? Tak. Dawać świadectwo o zmartwychwstałym Jezusie i zanieść Jego zbawienie do każdego człowieka. Dzisiaj wracamy do tego zadania, ale zaczynając od drugiej części – od ewangelizacji.

W czasie jednej z homilii w Domu Świętej Marty papież Franciszek mówił: „Nasi misjonarze, ci bohaterowie ewangelizacji naszych czasów. Europa, która wypełniła misjonarzami inne kontynenty. Oni wyjeżdżali bez możliwości powrotu. Myślę, że słuszne jest, byśmy dziękowali Bogu za ich świadectwo, byśmy cieszyli się tymi misjonarzami, którzy są prawdziwymi świadkami. Myślę o tym, jak wyglądał ich ostatni moment. Jak wyglądało ich pożegnanie? Tak jak Ksawery: zostawił wszystko, ale było warto! Tylu anonimowych, już odeszli. Inni byli męczennikami, czyli ofiarowali swoje życie dla Ewangelii. Ci misjonarze są naszą chwałą! Chwałą naszego Kościoła!”.

Słuchając tych słów, mam w pamięci misję, gdzie pracowałem, i groby pierwszych misjonarzy, którzy zmarli tam tak młodo. Widzę twarze polskich misjonarzy, męczenników, których znałem osobiście… Widzę też misjonarzy i misjonarki, których odwiedzałem: geniusze, giganci ducha, „spalający się” dzień po dniu dla ewangelizacji. Ale przede wszystkim ludzi pełnych radości, wewnętrznej wolności, zakorzenionych w Jezusie. Dziwne? Chyba nie. Papież w jednym z orędzi na Niedzielę Misyjną pisał: „Misje to pasja, którą żywimy wobec Jezusa i wobec ludzi. Gdy trwamy na modlitwie przed Jezusem ukrzyżowanym, to widzimy ogrom Jego miłości, która daje godność i nas umacnia, a równocześnie czujemy, że ta miłość, która wypływa z Jego przebitego serca, rozlewa się na cały Lud Boży i na całą ludzkość. Wtedy czujemy też, że On chce się nami posłużyć, aby przybliżać się coraz bardziej do swojego umiłowanego ludu oraz do tych, którzy Go szczerym sercem szukają”.

Moi drodzy! Wszyscy chyba znamy te ewangeliczne słowa: „Idźcie więc i nauczajcie wszystkie narody, udzielając im chrztu w imię Ojca i Syna, i Ducha Świętego. Uczcie je zachowywać wszystko, co wam przykazałem. A oto Ja jestem z wami przez wszystkie dni, aż do skończenia świata” (Mt, 28,19). W ich perspektywie misjonarze wciąż idą, a właściwie to Kościół ich posyła. A cel ciągle ten sam – zanieść Jezusa na krańce świata.

A my? Papież Franciszek przychodzi nam z odpowiedzią, zwracając się do młodych, czyli oczywiście do pielgrzymów Pieszej Pielgrzymki Tarnowskiej: „Chciałbym powiedzieć dzisiejszym chłopcom i dziewczętom, którzy nie czują się dobrze, którzy nie są zbyt szczęśliwi w tej kulturze konsumpcjonizmu, narcyzmu. Patrzcie aż po horyzont! Spójrzcie tam, na tych naszych misjonarzy! Trzeba modlić się do Ducha Świętego, aby uzdolnił ich do pójścia daleko, by «spalić» swoje życie. To może trochę mocne słowo, ale życie jest warte tego, by je przeżyć. Ale przeżyć je dobrze, «spalić» je w służbie, w głoszeniu Słowa, w dążeniu dalej. I to jest radość głoszenia Ewangelii”.

Ciekawe, że dzieło misyjne Kościoła można porównać do ludzkiego ciała. Głową, a zwłaszcza ustami są pasterze, którzy nauczają, iż Kościół jest autentyczny wówczas, kiedy idzie i głosi zbawienie w Chrystusie. Nogami są misjonarze, którzy wyruszyli tam, gdzie Ewangelia nie jest jeszcze znana. Z kolei sercem i krwiobiegiem są ci, którzy wspierają misyjne wysiłki swoją modlitwą, cierpieniem i wyrzeczeniem. Rękami wreszcie są dobroczyńcy misji, ci, którzy pomagają misjom materialnie.

Czy widzisz, że w tym organizmie, w tej wspólnocie, w której żyjesz, jest miejsce i zadanie dla Ciebie? Zapraszam, abyś dzisiaj szczególnie o tym pomyślał: mogę wspierać misje modlitwą, choćby na adoracji Najświętszego Sakramentu czy dołączając do żywego różańca. Może włączę się w organizowanie kolędników misyjnych? Może częściej wspomogę misje finansowo moimi skromnymi oszczędnościami? A może… czujesz, że i Ciebie Pan zaprasza i chce Cię posłać? Ojciec święty zachęca nas: „Każdy chrześcijanin i każda wspólnota winni rozeznać, jaką drogą powinni kroczyć zgodnie z wezwaniem Pana, jednak wszyscy jesteśmy zaproszeni do przyjęcia tego wezwania: wyjścia z własnej wygody i zdobycia się na odwagę, by dotrzeć na wszystkie peryferie potrzebujące światła Ewangelii”.

Moi bracia i siostry pielgrzymi! Ks. Marek Rybiński SDB, misjonarz zamordowany podczas swej posługi w Tunezji, którego znałem osobiście, w jednym z listów pisał: „Powiem wręcz, że nie czuję się misjonarzem będąc tutaj i chyba nawet dobrze, że nie otrzymałem krzyża misyjnego, bo byłoby to niesprawiedliwe wobec prawdziwych misjonarzy, którzy co dwa tygodnie chorują na malarię, leczą się na urlopach w kraju z różnych innych chorób, są wystawieni na wiele niebezpieczeństw i żyją czasami w bardzo opłakanych warunkach, myśląc, co włożyć sobie do garnka i jak zapewnić wyżywienie mieszkańcom wioski, w której pracują. Choć z drugiej strony, przecież nie tylko pusty garnek wyznacza rejony misyjne, duch misyjny to coś więcej niż troska o cierpiące dzieci Afryki, ale głód duchowy, a może przede wszystkim, właśnie to – nieznajomość Jezusa, to wyznacza rejony misyjne”.

Czyż nie miał racji? Pewnie, że tak. I w tej perspektywie staje przed Tobą i przede mną drugie, podstawowe zadanie Kościoła: dawać świadectwo o Jezusie i Jego miłosierdziu tu, gdzie postawiła nas Boża opatrzność, nawet jeśli otoczenie nie jest nam przychylne.

Z badań wynika, że blisko dwadzieścia procent katolików w Polsce spotkała się z unikaniem społecznym ze względu na wyznawaną przez nich wiarę; z wrogością spotkało się niemal dwadzieścia cztery procent badanych. Na pytanie, czy spotkałeś się z lekceważeniem ze względu na przyznawanie się do poglądów katolickich, twierdząco odpowiedziało czterdzieści trzy procent katolików.

Czy w takiej perspektywie można się wycofać? Odpowiedź daje nam o. E. Tardif: „Prawdziwy ewangelizator to ten, kto pokazuje swoje osobiste świadectwo i swoje doświadczenie zbawienia, kto może zaświadczyć, że Jezus żyje, ponieważ spotkał się z Nim, tak jak apostołowie, którzy głosili: «Bo my nie możemy nie mówić tego, cośmy widzieli i słyszeli» (Dz 4,20)”.

Kończąc, przytoczę fragmenty utworu o. Kazimierza Lubowieckiego OMI, które uczyńcie teraz, proszę, osobistą modlitwą powtarzaną w sercu:

„Naucz nas myśleć jak apostołowie. Przekonaj, że nie można milczeć o tym, co słyszeliśmy na własne uszy, czego dotykaliśmy rękami, z czym się serce związało. Niech za naszych dni powtórzy się cud Zielonych Świąt, niech wyjdą na drogi świata nowi apostołowie. Niech wyjdą, bo inaczej kamienie wołać będą… Twojej sprawy nie wystarczy wesprzeć kilkoma groszami, siedząc spokojnie w wygodnym domu. Nie można Ci służyć czasami, gdzieniegdzie, od święta. Twoja sprawa warta jest, by poświęcić jej życie. Całe własne życie. Naucz nas tylko patrzeć na świat jak na jedną rodzinę. I naucz nas troszczyć się o świat jak o własną rodzinę. I naucz nas drżeć, by nie zabrakło tej rodzinie powszedniego chleba – chleba, jakim jest Twoja Ewangelia. Amen”.
`;