export const day4Study = `
W Kościele i w Ojczyźnie

Dzisiaj znów zaczniemy od misyjnego wspomnienia. Kilka lat temu przyszło mi odwiedzić misję, w której kiedyś pracowałem. Dowiedziawszy się o tym, jeden z miejscowych katechistów – człowiek prawy, choć bardzo biedny – bardzo, ale to bardzo prosił mnie o pomoc finansową. Chciał bowiem kształcić swoje najmłodsze dziecko, ale po prostu nie miał za co. Niewiele myśląc, „zorganizowałem” pieniądze i przekazałem je przy naszym pierwszym spotkaniu. Jego radość była ogromna. Ale jeszcze większe było moje zdziwienie kilka dni później, kiedy tenże człowiek, chcąc wyrazić swoją ogromną wdzięczność, wręczył mi niewielki pakunek. I wiecie, co mi ofiarował? W małym zawiniątku były jego prawie nowe, czarne buty, jak my to mówimy w naszych stronach – półbuty. Tak bardzo był wdzięczny.

Dlaczego o tym wspominam? Dlatego, że ten człowiek – może w nieco zaskakujący dla nas sposób – pokazał, jak bardzo zależy mu na edukacji syna. Pokazał, że odpowiedzialnie realizuje obowiązki ojca. A znając go, mogę tylko dodać, że w takim też stylu pracował jako nauczyciel, katechista, chórzysta i członek tamtejszej rady gminy.

Papież Franciszek przyzwyczaił nas, że używa bardzo ciekawych porównań. W jednym z nich porównał Kościół do kolumnady na placu św. Piotra w Rzymie. Podkreślał przy tym, że my – ludzie wierzący – nie izolujemy się od innych. Żyjemy normalnie, chodzimy do szkoły, pracujemy, troszczymy się o nasze rodziny, realizujemy pasje, wypełniamy obowiązki społeczne i patriotyczne. W ten właśnie sposób dajemy innym nasze chrześcijańskie świadectwo. Papież pisał o tym tak: „Wszyscy jesteśmy powołani, by być świętymi, żyjąc z miłością i dając swe świadectwo w codziennych zajęciach, tam, gdzie każdy się znajduje. Jesteś osobą konsekrowaną? Bądź świętym, żyjąc radośnie swoim darem. Jesteś żonaty albo jesteś mężatką? Bądź świętym, kochając i troszcząc się o męża lub żonę, jak Chrystus o Kościół. Jesteś pracownikiem? Bądź świętym, wypełniając uczciwie i kompetentnie twoją pracę w służbie braciom. Jesteś rodzicem, babcią lub dziadkiem? Bądź świętym, cierpliwie ucząc dzieci naśladowania Jezusa. Sprawujesz władzę? Bądź świętym, walcząc o dobro wspólne i wyrzekając się swoich interesów osobistych”.

Zadanie jasne, ale i wymagające. Dobrze o tym wiemy z własnego doświadczenia. Warto jednak popatrzeć na tych, którym się to udało.

Na przykład św. Josemaria Escriva uczył następująco. Po pierwsze: trzeba wykonywać swoje obowiązki z największą doskonałością, z miłości do Boga, w zjednoczeniu z Nim. Po drugie: czyniąc tak, pozwalamy, żeby sam Duch Święty nas uświęcał. I po trzecie: tak realizując nasze życiowe zadania, przemieniamy i uświęcamy innych i świat wokół nas.

Z kolei bł. Józef Allamano zachęcał, żeby dobrze czynić każdą rzecz, dobrze czynić dobro, być nadzwyczajnym w zwyczajności.

Błogosławiony Pier Giorgio Frassati studiował inżynierię górniczą, a z przyjaciółmi założył „Stowarzyszenie Ciemnych Typów”, którego celem była modlitwa i górskie wędrówki.

Błogosławiony Carlo Acutis był zapalonym piłkarzem, grał na saksofonie i budował strony internetowe o cudach eucharystycznych, a także o świętych.

A nasza bł. Karolina Kózkówna? A beatyfikowana przed rokiem rodzina Ulmów? Zwyczajni ludzie, zakochani w Jezusie, którzy realizowali z pasją swoje życiowe powołanie. Aż po męczeństwo.

Może te wzory wydają się nam zbyt odległe, trudne do naśladowania. Na szczęście papież Franciszek przypomina: „Nie można się więc zniechęcać, podziwiając wzory świętości, które wydają się nieosiągalne. Istnieją świadectwa przydatne, by nas pobudzić i motywować, ale nie dzięki temu, że próbujemy je kopiować (…). Liczy się to, aby każdy wierny rozpoznał swoją drogę i wydobył z siebie to, co ma najlepszego, to, co najbardziej osobistego Bóg w nim umieścił (por. 1 Kor 12,7), a nie marnował sił, usiłując naśladować coś, co nie było dla niego pomyślane”.

Pięknie taką właśnie postawę opisała św. Teresa od Dzieciątka Jezus: „Jezus raczył pouczyć mnie o tej tajemnicy. Stawił mi przed oczyma księgę natury i zrozumiałam, że wszystkie kwiaty przez Niego stworzone są piękne, że przepych róży i biel lilii nie ujmują woni małemu fiołkowi ani zachwycającej prostoty stokrotce… Zrozumiałam, że gdyby wszystkie małe kwiatki chciały być różami, natura straciłaby swą wiosenną krasę, pola nie byłyby umajone kwieciem… Podobnie dzieje się w świecie dusz, w tym ogrodzie Jezusa. Spodobało Mu się stworzyć wielkich świętych, których można porównać do lilii i róż; lecz stworzył także tych najmniejszych, którzy winni się zadowolić, że są stokrotkami i fiołkami, przeznaczonymi, by radować oczy dobrego Boga, gdy je skieruje na ziemię. Doskonałość polega na tym, by czynić Jego wolę, by być tym, czym On nas chce mieć”.

Inny święty, Maksymilian Maria Kolbe, tak był z kolei zdeterminowany, że nawet w listach do swojej mamy pisanych z okazji świąt życzył jej nie tyle zdrowia i pomyślności, ale właśnie tego, by wypełniła Bożą wolę.

Jezus zaprasza także i mnie, abym realizował na co dzień to, czego On sam ode mnie oczekuje. On ma najlepszy plan na moje życie i na moją drogę do świętości. Trzeba tylko Jemu zaufać! Mocno trzymać się Jego dłoni! I często pytać Ducha Świętego, co i jak mam czynić, aby Jezus mógł w pełni działać we mnie i przeze mnie. Zachęca do tego ojciec święty Franciszek słowami: „Także ty powinieneś pojmować całe swe życie jako misję. Spróbuj tego, słuchając Boga na modlitwie i rozpoznając znaki, jakie On ci daje. Zawsze pytaj Ducha Świętego, czego Jezus oczekuje od ciebie w każdej chwili twojego życia i w każdej decyzji, którą musisz podjąć, aby rozeznać miejsce, jakie zajmuje dana kwestia w twojej własnej misji”.

Moi drodzy! Pielgrzymujemy pod hasłem: „Żyję w Kościele”. Żyję we wspólnocie, którą założył i w której jest i działa sam Jezus. To On pragnie naszego szczęścia i naszej świętości. Zaprośmy Go na nowo, pozwólmy, aby On sam nas poprowadził tak, aby spełniały się na nas słowa papieża Franciszka: „Lubię dostrzegać świętość w cierpliwym ludzie Bożym: w rodzicach, którzy z wielką miłością pomagają dorastać swoim dzieciom, w mężczyznach i kobietach pracujących, by zarobić na chleb, w osobach chorych, w starszych zakonnicach, które nadal się uśmiechają. W tej wytrwałości, aby iść naprzód, dzień po dniu, widzę świętość Kościoła walczącego. Jest to często «świętość z sąsiedztwa», świętość osób, które żyją blisko nas i są odblaskiem obecności Boga, albo, by użyć innego wyrażenia, są «klasą średnią święto-ści»”.
`;