export const day5study = `
Kościół karmi mnie Eucharystią

Amerykański pisarz Julien Green szukał argumentów, by przyjąć wiarę katolicką. W tym celu stawał przy drzwiach jednego z kościołów i obserwował ludzi wychodzących po Mszy św. Mówił sobie, że jeśli ci ludzie rzeczywiście wierzą, to na pewno wyjdą z rozpromienionymi twarzami. Tymczasem gorzko zauważał: „Schodzą z Kalwarii i znudzeni ziewają”. Zastanawiające, prawda? Przecież oni spotkali przed chwilą Jezusa, słuchali Go i przyjęli Go do serca! Czyżby nie odczuli Jego miłości? A może trzeba postawić sprawę inaczej?

A ja, jak przeżywam Eucharystię? Przed kilkoma laty przeżywaliśmy wszyscy trudny czas – niezapomniany, bo naznaczony pandemią Covid-19. Nasza rodaczka, pani Agnieszka z Tarnowa, tak go wspomina: „Przeżycie rodzinnej Mszy św. on-line dla mnie i mojego męża było niezwykle wzruszającym doświadczeniem. Widok księży odprawiających Mszę św. w prawie pustym kościele był dla mnie przejmujący. Nawet teraz nie jestem w stanie pohamować łez, kiedy o tym piszę. Tęsknota za przyjęciem Komunii św. i za żywą modlitewną wspólnotą – to uczucia, które mam w sercu. Myślę, że ta nowa sytuacja pozwoli zrewidować też naszą postawę wobec kapłanów – trzeba dziękować, że są, i modlić się o nowe powołania. Obyśmy nigdy nie musieli być skazani tylko na wirtualne nabożeństwa”.

W kontekście tych dwóch świadectw pragnę Was zaprosić, abyśmy duchowo poszli teraz na Mszę św. i na adorację. Naszymi przewodnikami będą mistycy, którzy otrzymali szczególne doświadczenia eucharystyczne. A zatem – idziemy. Wchodzimy do kościoła i słyszymy Maryję mówiącą do Cataliny Rivas: „Dlaczego przychodzicie w ostatnim momencie? Powinniście tu być już wcześniej, by się pomodlić i prosić Pana, aby posłał wam swojego Świętego Ducha, aby obdarzył was duchem pokoju, który wypędza z was ducha tego świata, niepokoje, problemy i rozproszenia, abyście mogli w ten sposób przeżywać ten święty czas. Wy natomiast wpadacie prawie z początkiem Mszy, uczestniczycie w niej jakby to było zwyczajne wydarzenie, bez żadnego duchowego przygotowania. Dlaczego?”. Postanawiamy poprawę i już chcemy się dalej modlić, ale znów słyszymy: „Z głębi twojego serca proś Pana o wybaczenie wszystkich twoich win, za to, że Go obraziłaś, abyś mogła godnie uczestniczyć w przywileju, jakim jest ta Msza św.”. Siadamy, aby słuchać Bożego słowa, a właściwie, aby słuchać Jezusa, który do nas w tym słowie będzie się zwracał. Pamiętacie naszą drugą pielgrzymkową refleksję o Słowie? Bądźmy skupieni i otwarci…

A teraz ofiarowanie. Chleb i wino, kapłan, ministranci i… co to za postacie? „Patrz, to Aniołowie Stróżowie każdej z osób, które tu się znajdują. W tym momencie wasz Anioł Stróż zanosi wasze ofiary i modlitwy do ołtarza Pańskiego”. A zaraz potem śpiew: „Święty, święty”… i znów wiele osób, pięknych, o których Maryja mówi: „To wszyscy Święci i Błogosławieni Nieba, a wśród nich są też dusze waszych bliskich zmarłych, którzy cieszą się już oglądaniem Boga”. Nadchodzi najważniejszy moment Mszy św. – przeistoczenie. Po słowach konsekracji ksiądz podnosi ciało i krew Zbawiciela, a my wraz z Cataliną słyszymy: „Powtarzam ci, jest to najcudowniejszy z cudów. Dla Pana nie istnieje ani czas, ani przestrzeń. W chwili Konsekracji całe zgromadzenie staje u stóp Kalwarii w momencie ukrzyżowania Jezusa”. Serca przepełnia nam wdzięczność. Nadal się modlimy, uczestnicząc w kolejnych etapach Najświętszej Ofiary. I wreszcie przyjmujemy Jezusa w Komunii św. Tak jak Marta Robin, która przez 53 lata nie przyjmowała innego pokarmu, jak tylko Eucharystię, i mówiła: „Jezus ustanowił sakrament Eucharystii nie tylko po to, byśmy Go adorowali, ale również i po to, aby być pokarmem dla naszego ciała”. Co odczuwamy? To samo co św. Teresa, która po Pierwszej Komunii św. wspominała: „Był to pocałunek miłości; czułam, że jestem kochaną i sama również mówiłam: «Kocham Cię, oddaję się Tobie na zawsze»”. Dzięki Bogu, jeśli właśnie tak przeżywamy to spotkanie. Bo w przeciwnym razie mogłyby odnosić się do nas słowa samego Jezusa, który żalił się do Cataliny, mówiąc o kobiecie, która przed chwilą przyjęła Go do serca: „Zwróciłaś uwagę na to, że ani razu nie powiedziała Mi, że Mnie kocha? Nie podziękowała Mi za dar, jaki jej dałem, że uniżyłem się w Mojej Boskości, aby ją podnieść do siebie. Ani razu nie powiedziała: dziękuję, Panie. Była to litania próśb…, prawie wszyscy, którzy Mnie przyjmują, robią podobnie. Umarłem z miłości i zmartwychwstałem. Z miłości czekam na każdego z was i z miłości z wami pozostanę…, ale wy nie zdajecie sobie sprawy, że i Ja potrzebuję waszej miłości. Pamiętaj, że jestem Żebrakiem Miłości w tej wzniosłej chwili dla twojej duszy”.

A może trzeba, żebyśmy usłyszeli słowa Pana do św. Faustyny: „Ach, jak Mnie boli, że dusze tak mało się łączą ze Mną w Komunii św. Czekam na dusze, a one są dla Mnie obojętne. Kocham je tak czule i szczerze, a one Mi nie dowierzają. Chcę je obsypać łaskami – one przyjąć ich nie chcą. Obchodzą się ze Mną jak z czymś martwym, a przecież mam serce pełne miłości i miłosierdzia”. Tak łatwo zapominamy o obietnicy Zbawiciela: „Kto spożywa moje Ciało i pije moją Krew, ma życie wieczne, a Ja go wskrzeszę w dniu ostatecznym. Ciało moje jest prawdziwym pokarmem, a Krew moja jest prawdziwym napojem. Kto spożywa moje Ciało i Krew moją pije, trwa we Mnie, a Ja w nim (J 6,53-56)”. Nadchodzi czas, aby iść. Idziemy, jak mówi kard. Krajewski, jako „nosiciele Boga”, jako żywe tabernakula. Idziemy, aby w naszych codziennych sprawach, w realizacji naszego życiowego powołania być świadkami Zmartwychwstałego. By życiem pokazywać innym, Kogo spotkaliśmy i Kogo mamy w sercu. Papież Franciszek tak mówi o tym zadaniu: „Eucharystia uzdrawia, ponieważ jednoczy nas z Jezusem: sprawia, że przyswajamy sobie Jego sposób życia, Jego zdolność do łamania siebie i dawania siebie braciom, do odpowiadania dobrem na zło. Daje nam odwagę, aby wyjść poza swoje ograniczenia i pochylić się z miłością nad słabościami innych. Tak jak Bóg czyni to z nami. Taka jest logika Eucharystii: przyjmujemy Jezusa, który nas kocha i leczy nasze słabości, aby kochać innych i pomagać im w ich słabościach”.

Trzeba nam też posłuchać św. Jana Pawła II, który zachęcał: „Kościół i świat odczuwają wielką potrzebę kultu eucharystycznego. Jezus oczekuje nas w tym Sakramencie miłości. Nie żałujmy naszego czasu na spotkanie z Nim w adoracji, na kontemplację pełną wiary i gotowości wynagrodzenia wielkich win i występków świata”. Szukajmy okazji, aby z Nim być, bo przecież dobrze wiemy, ile razy marnujemy czas. Jezus żali się do Cataliny: „Ludzie planują swój dzień, tydzień, semestr, wakacje itd. Wiedzą, którego dnia będą odpoczywali i kiedy pójdą do kina lub na przyjęcie, odwiedzić babcię, wnuki, dzieci, przyjaciół, kiedy pójdą się zabawić. A ile rodzin mówi przynajmniej raz w miesiącu: «To jest dzień, kiedy pójdziemy odwiedzić Jezusa w Tabernakulum» i całą rodziną przychodzą porozmawiać ze Mną, siadają przy Mnie i opowiadają mi o tym, co się wydarzyło w ostatnich dniach, o problemach i trudnościach, które noszą w sercu. Zapraszają Mnie do uczestnictwa w swoim życiu! No, ile razy?”.

Drodzy pielgrzymi! Pewnego razu w czasie wakacji, kiedy byłem jeszcze klerykiem, jechałem z pewnym księdzem do parafii leżącej na drugim krańcu naszej diecezji. Zaskoczył mnie fakt, że przy każdym mijanym kościele czynił znak krzyża, a czasem odmawiał: „Niechaj będzie pochwalony Przenajświętszy Sakrament…”. Im więcej lat upłynęło, tym bardziej odkrywam tę jego wiarę i konkretną wrażliwość na obecność Jezusa w Eucharystii. A my? Mijamy nieraz tyle kościołów. Nie chodzi mi tylko o czas pielgrzymki… Czy pamiętam wówczas o Panu? Wejdę do Niego na minutę czy dwie? A może choć w myślach przeniosę się na ułamek sekundy do Niego i powiem: Panie, dziękuję, że tu jesteś, że czekasz, że kochasz nieustannie… Bracia i siostry pielgrzymi! Może zaskoczyła Was forma naszej dzisiejszej refleksji? Tego nie wiem. Wiem natomiast – i Wy też to wiecie – że jeśli nasze spotkanie z Jezusem w Eucharystii będziemy przeżywać jak najczęściej i tak, jak On tego od nas oczekuje – to z pewnością będziemy szczęśliwi. I będziemy przepiękną cząstką Kościoła, w którym żyjemy i którym jesteśmy!

Pomyśl o tym, tym bardziej że w ostatnim okresie Jezus aż dwa razy przypomniał w Polsce o swojej eucharystycznej, rzeczywistej obecności. W 2008 r. – w Sokółce, i w 2013 r. – w Legnicy. Czy to nie szczególne zaproszenie dla Ciebie, dla mnie, dla nas?
`;