export const day6Study = `
Kościół głosi i wyprasza Boże miłosierdzie

Przed kilkoma laty miałem szczęście odwiedzić Mongolię i spotkać żyjących tam katolików. Wspólnota katolicka w tym potężnym kraju liczy zaledwie tysiąc pięćset osób. Oficjalnie nie można ewangelizować. A zatem nowi wyznawcy Jezusa pojawiają się, bo zachęcił ich kolega, bo zaciekawiło ich, jak zmieniło się postępowanie i rytm życia sąsiadów. I jeszcze coś – orędzie o miłosierdziu Bożym. Z radością i ze wzruszeniem patrzyłem, jak ks. Giorgio po niedzielnej Eucharystii rozdawał obrazki „Jezu, ufam Tobie” z napisem po mongolsku. Następnie miała miejsce katecheza o Bożym miłosierdziu zakończona odmówieniem koronki. Dlaczego o tym wspominam? Czy zwróciliście uwagę na fakt, że Jezus pragnął, aby orędzie o Bożym miłosierdziu dotarło na cały świat? Święta siostra Faustyna zanotowała w swoim Dzienniczku: „ujrzałam Pana Jezusa ubranego w szacie białej. Jedna ręka wzniesiona do błogosławieństwa, a druga dotykała szaty na piersiach. Z uchylenia szaty na piersiach wychodziły dwa wielkie promienie, jeden czerwony, a drugi blady. (…) Po chwili powiedział mi Jezus: «Wymaluj obraz według rysunku, który widzisz, z podpisem: ‘Jezu, ufam Tobie’. Pragnę, aby ten obraz czczono najpierw w kaplicy waszej i na całym świecie»” (Dz. 47). Z kolei, ustanawiając specjalne święto, które dziś znamy jako Niedzielę Miłosierdzia Bożego, Pan Jezus wyraził takie pragnienie: „W święto Moje, w święto Miłosierdzia będziesz przebiegać świat cały i sprowadzać będziesz dusze zemdlone do źródła miłosierdzia Mojego. Ja je uleczę i wzmocnię” (Dz. 206).

Nie inaczej było, kiedy św. Faustyna usłyszała słowa wspomnianej już wcześniej koronki do Bożego Miłosierdzia. Jezus zapraszał ją do modlitwy: „Ojcze Przedwieczny, ofiaruję Ci Ciało i Krew, Duszę i Bóstwo najmilszego Syna Twojego, a Pana naszego Jezusa Chrystusa, na przebłaganie za grzechy nasze i świata całego”, oraz: „Dla Jego bolesnej męki miej miłosierdzie dla nas i świata całego” (Dz. 476). „Kościół żyje swoim autentycznym życiem, kiedy wyznaje i głosi miłosierdzie – najwspanialszy przymiot Stwórcy i Odkupiciela” – mówił św. Jan Paweł II. I faktycznie – orędzie to jest głoszone chyba na całym świecie. Wszędzie, gdzie mogłem odwiedzać polskich misjonarzy, widziałem, jak wiele serca wkładają, aby naszych braci i siostry poprowadzić do Jezusa Miłosiernego. I Bogu dzięki! W tej perspektywie trzeba jednak, abyśmy uświadomili sobie coś niezwykle istotnego. Każdy z nas może, a nawet powinien przyczyniać się do tego, aby Boże miłosierdzie było głoszone bez względu na granice polityczne czy systemy kulturowe. Prosił o to wspominany już Jan Paweł II, kiedy po raz ostatni pielgrzymował do Polski. Mówił wtedy: „Trzeba tę iskrę Bożej łaski rozniecać. Trzeba przekazywać światu ogień miłosierdzia. W miłosierdziu Boga świat znajdzie pokój, a człowiek szczęście! Zadanie powierzam wam, drodzy bracia i siostry, Kościołowi w Krakowie i w Polsce oraz wszystkim czcicielom Bożego Miłosierdzia”. Moi drodzy! Ty i ja jesteśmy zaproszeni, aby być apostołami Bożego miłosierdzia, aby wypraszać je dla świata. I nawet nie musimy szukać nadzwyczajnych sposobów. Zacznijmy od tego, aby odmawiając koronkę, zawrzeć w tej modlitwie nie tylko nasze sprawy i intencje. Bądźmy wrażliwi i z otwartym sercem módlmy się z ufnością: „miej miłosierdzie dla nas i całego świata”. I z pewnością wchodząc któregoś dnia do nieba, na jego progu spotkamy nie tylko Jezusa szeroko otwierającego ramiona. Nie tylko Maryję i naszych bliskich – już świętych. Ale i wielu ludzi z różnych zakątków świata, którzy powiedzą nam: „Dziękuję”.

Pomódlmy się zatem słowami św. Jana Pawła II: „Boże Ojcze miłosierny, który objawiłeś swoją miłość w Twoim Synu Jezusie Chrystusie i wylałeś ja na nas w Duchu Świętym, Pocieszycielu, Tobie zawierzamy dziś losy świata i każdego człowieka. Pochyl się nad nami grzesznymi, ulecz naszą słabość, przezwycięż wszelkie zło, pozwól wszystkim mieszkańcom ziemi doświadczyć Twojego miłosierdzia, aby w Tobie, Trójjedyny Boże, zawsze odnajdywali źródło nadziei. Ojcze przedwieczny, dla bolesnej męki i zmartwychwstania Twego Syna, miej miłosierdzie dla nas i całego świata!”. Bracia i siostry pielgrzymi! Ojciec święty Franciszek pisał: „Miłosierdzie to najwyższy i ostateczny akt, w którym Bóg wychodzi nam na spotkanie (…). Miłosierdzie to droga, która łączy Boga z człowiekiem, ponieważ otwiera serce na nadzieję, że będziemy kochani na zawsze, pomimo ograniczenia, jakim jest nasz grzech”. Kiedy tę prawdę sobie uświadamiamy, kiedy nią żyjemy, wtedy tym bardziej wzrasta w nas pragnienie, aby to doświadczenie stało się udziałem innych.

Prawda ta prowadzi nas także do drugiej – fundamentalnej dla nas postawy – do ufności w Boże Miłosierdzie. Nasze doświadczenie uczy nas jednak bardzo wyraźnie, że łatwiej powtarzać: „Jezu, ufam Tobie”, niż faktycznie całkowicie Panu zawierzyć. Widać to zwłaszcza, kiedy się o coś żarliwie modlimy, ale gdzieś „z tyłu głowy” mamy nadzieję, że Jezus postąpi tak, jak my tego oczekujemy.

Ojciec Tardif komentował niegdyś takie postawy, przypominając, iż kiedy się modlimy, nie jest najważniejsze, abyśmy otrzymali łaski, których pragniemy. Ważniejsze jest, aby modlić się z zaufaniem, że „Pan zadba o nasze życie lepiej od nas samych, w mierze większej, niż możemy to sobie wyobrazić. On czyni wszystko zgodnie ze swoją Wszechmocą i nieskończoną mądrością”. Zaufać Panu, powierzyć Mu siebie i swoje życie, to nie tylko domena modlitwy. To najlepszy pomysł i sposób na przepiękne przeżywanie swojego życia i realizację swego powołania. To wspaniała odpowiedź na Boże miłosierdzie, które nas ogarnia w każdej chwili. Jeśli ufam Panu, to mogę być pewien, że jestem w Jego rękach, że On mnie poprowadzi przez życie najlepszą drogą. Nawet jeśli teraz czegoś nie rozumiem albo przyszło mi przeżywać bardzo trudne chwile, to wiem, że kiedyś tam, w niebie, przekonam się, że to jednak Jezus miał rację.

Wracamy tutaj do tego, co rozważaliśmy w minionych dniach naszego pielgrzymowania. Jak ważnym jest, aby karmić się Słowem Jezusa, aby Go adorować, nasłuchując delikatnych i pełnych miłości natchnień, które nam daje. Jakże istotne jest przyzywanie Ducha Świętego. W taki właśnie sposób łatwiej rozpoznać tę drogę, na której kochający Jezus chce nas formować w Kościele, prowadzić i uświęcać. On pragnie naszego szczęścia, pragnie nas zbawić. Kończąc, chcę wam zaproponować pełną ufności modlitwę św. Karola de Foucauld. „Mój Ojcze, powierzam się Tobie. Uczyń ze mną, co zechcesz. Cokolwiek uczynisz ze mną, dziękuję Ci. Jestem gotów na wszystko, przyjmuję wszystko, aby Twoja wola spełniała się we mnie i we wszystkich Twoich stworzeniach. Nie pragnę nic więcej, mój Boże. W Twoje ręce powierzam ducha mego z całą miłością mego serca. Kocham Cię i miłość przynagla mnie, by oddać się całkowicie w Twoje ręce, z nieskończoną ufnością, bo Ty jesteś moim Ojcem”.

Moi drodzy! Pewnie daleko nam jeszcze, a mi z pewnością – do takiego zaufania i zawierzenia. Ale mimo naszych lęków, upadków czy wątpliwości niech nas wciąż mobilizuje Boże miłosierdzie, w którym jesteśmy zanurzeni każdego dnia (por. Dz. 17; 28). I niech nas inspirują słowa samego Pana: „Twoim obowiązkiem jest zupełna ufność w dobroć Moją, a moim obowiązkiem jest dać ci wszystko, czego potrzebujesz. Czynię się sam zależny od twojej ufności, jeśli ufność twoja będzie wielka, to hojność Moja nie będzie znać miary” (Dz. 548).
`;