export const day7Study =  `
Kościół jest miłosierny

Mówiliśmy wczoraj, że odpowiedzią na miłosierną miłość, którą obdarza nas Chrystus, jest wypraszanie miłosierdzia dla świata i zaufanie Jezusowi. Ta nasza odpowiedź byłaby niepełna, gdyby zabrakło jeszcze jednego wymiaru – sami mamy okazywać miłosierdzie. W Ewangelii według św. Mateusza Jezus prosi nas przecież: „Chcę raczej miłosierdzia niż ofiary” (Mt 9,13). Co więcej, zwracając się do św. Faustyny, wyjaśnia, że każdy może i powinien być miłosierny: „Miłosierdzie masz okazywać zawsze i wszędzie bliźnim. Nie możesz się od tego usunąć, ani wymówić, ani uniewinnić. Podaję ci trzy sposoby czynienia miłosierdzia bliźnim: pierwszy – czyn, drugi – słowa, trzeci – modlitwa; w tych trzech stopniach zawiera się pełnia miłosierdzia i jest niezbitym dowodem miłości ku Mnie” (Dz. 742).

Moi drodzy! Ponad dwadzieścia lat temu Jan Paweł II mówił w Krakowie: „Potrzeba wyobraźni miłosierdzia wszędzie tam, gdzie ludzie w potrzebie wołają do Ojca Miłosiedzia. Pomóżcie współczesnemu człowiekowi zaznać miłosiernej miłości Boga!”. No właśnie! Ta osoba, która otrzymuje Twoje materialne wsparcie czy też cieszy się z Twoich odwiedzin, tak naprawdę – może nie do końca świadomie – odczuwa bliskość i miłosierdzie Boga, który nie odrzuca nikogo! Który pamięta! Papież Franciszek przypomina nam o tym przez swoje decyzje, gesty i ciekawe porównania. Może pamiętamy, że porównał Kościół – czyli nas – do szpitala polowego. Innym razem mówił, że mamy być jak rower, który jeśli nie jedzie, to zaraz straci równowagę. Mówił także: „Relacje Jezusa z osobami, które Go otaczają, cechuje coś jedynego w swoim rodzaju i niepowtarzalnego. Znaki, które czyni, przede wszystkim w stosunku do grzeszników, ubogich, odrzuconych, chorych i cierpiących, wyrażają miłosierdzie. Wszystko w Nim mówi o miłosierdziu. Nic w Nim nie jest wyzute ze współczucia”.

Doskonałym drogowskazem na drodze okazywania bliźnim miłosierdzia są katechizmowe Uczynki miłosierne wobec ciała i duszy. Jasne, że w tej refleksji nie będziemy ich wszystkich analizować. Zachęcam Was jednak, aby o nich na serio pomyśleć i przejrzeć się w ich świetle w tylu konkretnych sytuacjach z przeszłości czy teraz – z pielgrzymkowej rzeczywistości. A zanim się nimi zajmiemy, chcę Ci podziękować. Tobie! Za miłosierdzie, które okazywałeś – modlitwą, dobrym słowem, włączając się w zbiórkę, jako wolontariusz… Często bardzo ofiarnie i dyskretnie. Dziękuję za piękną postawę ukazującą miłosiernego Jezusa i żywy Kościół!

A teraz już wróćmy do drogowskazu. Najpierw uczynki co do ciała. Te, które wypełniamy, dając swój czas, pieniądze, pracę, coś materialnego. Dobrze jest pomagać w sposób zorganizowany, przez instytucje i osoby zajmujące się tym na co dzień. Jasne. A w sytuacji, kiedy ktoś bezpośrednio mnie prosi? Bezdomny, bo jest głodny; chory, żebym załatwił mu taką czy inną sprawę? Ojciec święty i jego jałmużnik kard. Krajewski podpowiadają, żeby zastanowić się, co w danej sytuacji zrobiłby Jezus. Bo przecież każda sytuacja jest inna i wymaga różnych decyzji. Trudno przecież dać dwa złote pijanemu żebrakowi, który prosi, choć już nie jest w stanie utrzymać się na nogach. Mimo to można okazać mu miłosierdzie. Westchnij za nim do Jezusa. Zrób to od razu, bo za chwilę już o nim zapomnisz. Rób tak zawsze, kiedy widzisz kogoś w potrzebie. I nie oceniaj go, nie przekreślaj. Bóg go kocha tak samo jak Ciebie.

Przy okazji warto tu wspomnieć bł. Józefa Allamano, który pisał właśnie o ocenianiu drugich: „«Człowiek patrzy na to, co zewnętrzne, Pan patrzy na serce» (1 Sm 16,7). Tym-czasem nawet jeśli widzimy wyraźnie to, co jest złe, powinniśmy wytłumaczyć, usprawiedliwić, wybaczyć złą intencję, ignorancję lub nieuwagę czy roztargnienie”.

Jezus mówi nam: „Błogosławieni miłosierni, albowiem oni miłosierdzia dostąpią” (Mt 5,7). Miłosierni w wymiarze materialnym, w tym, co można zmierzyć, policzyć, zobaczyć. Ale i nie mniej miłosierni w przestrzeni ducha: grzeszących upominać, nieumiejętnych pouczać. To trudne zadanie, bo sami grzeszymy i błądzimy. Ale właśnie dzięki temu, że żyjemy w Kościele, stale mamy okazję się korygować – słuchając Kościoła - matki i z otwartością przyjmując osobę, która delikatnie i z autentyczną miłością mi pomoże. Dlatego też i my możemy się stać znakiem dla innych. Św. Maksymilian wspominał nawet, że inni mają prawo do naszego dobrego przykładu. A jeśli nasze świadectwo jest czytelne, to ktoś, może po latach, ale z niego skorzysta. Miłosierdzie Boże jest przecież nieskończone. „Każdy chrześcijanin, na tyle, na ile się uświęca, staje się bardziej owocny dla świata” – przypomina papież Franciszek.

Są też sytuacje, kiedy sumienie nam podpowiada, że trzeba powiedzieć delikatnie, ale z przekonaniem. I nie wolno nam się tłumaczyć, że „ona się obrazi” albo „co też on sobie pomyśli – że wchodzę z butami w jego życie”. Pomyśl: lekarz, który operuje, musi zadać ból. Ale to, co z tym bólem jest związane, poprawi zdrowie, a nawet uratuje życie. I pamiętaj: nie chodzi o „dręczenie” kogoś nieustannymi wymówkami, bo skutek będzie odwrotny.

A jeśli znajdujemy się w sytuacji, kiedy trzeba wątpiącym dobrze radzić, a strapionych pocieszać? Ojciec święty daje nam tutaj czytelną wskazówkę: „Jezus się nie oszczędza, ale wręcz wdaje się w cierpienie i potrzeby ludzi, bo po prostu potrafi i pragnie współcierpieć, bo ma serce, które nie wstydzi się tego, że współczuje”. Tych słów nie trzeba chyba komentować wśród ludzi, którzy idą za Jezusem we wspólnocie Kościoła.

Przed nami kolejne wyzwanie. „Krzywdy cierpliwie znosić” – i tu od razu dodam: sam nie dasz rady. Tylko z Jezusem, jedynie, kiedy Jemu zaufasz. Z Nim dasz radę, bo wszystko możesz w Tym, który cię kocha i umacnia (por. Flp 4,13).

A darować urazy, przebaczyć? Pamiętasz, jak czytaliśmy o bł. Lucjanie Botovasoa? A ja pamiętam wspomniane już siostry z Burundi. Opowiadały one o pewnej kobiecie, której w plemiennym konflikcie zabito męża i wszystkie dzieci. Jakiś czas później przyszła prosić o różaniec, mówiąc: „Ja im przebaczyłam, a teraz będę się modlić o ich nawrócenie”. Czym innym jest pamiętać o tym, co się wydarzyło, a czym innym przebaczyć.

Ojciec święty Franciszek powiedział kiedyś w południowej modlitwie Anioł Pański, że Jezus nie tylko czynił miłosierdzie – On „cały jest Miłosierdziem”. Wystarczy popatrzyć na Jego życie, śmierć i na to, ile i co nam już w życiu wybaczył…

I na koniec – pamięć o zmarłych. W czasie Światowych Dni Młodzieży w Polsce, w rodzinnej parafii w Tymbarku miałem okazję spotkać grupę młodych Francuzów. Wiecie, co ich najbardziej zaskoczyło? To, że w naszych parafiach jest tylu młodych, i to, że po niedzielnej Mszy św. prawie wszyscy idą na cmentarz. To jest nasze świadectwo. To jest świadectwo Kościoła – wbrew różnym opiniom – żywego Kościoła. I aby o tej „wyobraźni miłosierdzia” względem zmarłych nigdy nie zapominać, przywołam św. Faustynę. W jednej z wizji zobaczyła zmarłą, bardzo cierpiącą siostrę ze swego zgromadzenia. Zaczęła więc intensywnie za nią się wstawiać. Po jakimś czasie siostra ta przyszła znowu do Faustyny, ale już z rozpromienioną twarzą. Powiedziała też, że s. Faustyna ma prawdziwą miłość bliźniego i że z jej modlitw także wiele innych dusz skorzystało (por. Dz. 58).

Bracia i siostry! Sam Jezus przez św. Jakuba Apostoła przypomina, że kiedyś Bóg zapyta o nasze życie i że „będzie to sąd nieubłagany dla tego, który nie czynił miłosierdzia” (por. Jk 2,13). A papież Franciszek, chcąc jakby uchronić nas przed obawami, a jednocześnie przypomnieć nam, jak wielkim szczęściem jest naśladowanie miłosierdzia Jezusa i co to znaczy prawdziwie być Kościołem, pisze: „Miłosierdzie Boga jest Jego odpowiedzialnością za nas. On czuje się odpowiedzialny, czyli pragnie naszego dobra i chce, byśmy byli szczęśliwi, napełnieni radością i pokojem. W tym samym kierunku powinna zmierzać miłość miłosierna chrześcijan. Tak jak kocha Ojciec, tak też powinny kochać dzieci. Jak On jest miłosierny, tak też i my jesteśmy wezwani, by być miłosierni – jedni wobec drugich”.
`;