export const day8Study = `
Kościół i przebaczenie grzechów

Dzisiejszą refleksję rozpocznę od fragmentu świadectwa, które przeczytałem w jednym z tygodników katolickich. „W Kościele zawsze było także zło. Była pszenica, ale był i kąkol. Albo i gorsze chwasty. Przez te dwa tysiące lat swojego istnienia przeszedł różne okresy. Wiemy o wszystkich «czarnych kartach Kościoła» (notabene – też warto by się im uczciwie przyjrzeć), o schizmach, grzesznych papieżach, wojnach religijnych.

Co więc powoduje, że tak wielu z nas teraz deklaruje: «Od kilku lat nie chodzę do kościoła, choć wierzę w Boga»? Czym dla nas jest Kościół? Czym są sakramenty? Za co jesteśmy w stanie z nich zrezygnować? To jest cały czas ten sam Kościół! Kościół Jezusa Chrystusa. Kościół świętych i męczenników. Kościół, który prześladował i był prześladowany. Popełniał i popełnia straszne błędy. I inspiruje do największej świętości. Oddawania życia, ofiarnej, bezinteresownej służby. Który pozwala spotkać się z największą, najpiękniejszą nadzieją, jaka tylko może zaistnieć w ludzkim sercu. Ja spotkałam Chrystusa w Kościele. Dlatego wiem, że On tu jest. Jeśli jest dla mnie – jest dla każ-dego człowieka”.

 Ciekawa refleksja, prawda? Żyjemy w Kościele, który jest święty świętością samego Boga, ale i grzeszny z powodu naszych słabości. „Święty Kościół grzesznych ludzi”, którym jesteśmy, otrzymał jednak niezwykłą pomoc – sakrament pokuty. W dzisiejszej refleksji właśnie nad nim się zatrzymamy. Posłuchajcie świadectwa… „Doświadczyłam prawdziwego cudu. Jest nim właśnie miłosierdzie Boże, które ogarnia każdego, nikogo nie opuści. Jest codziennie, nieustannie darem dla nas. Chcę podzielić się z Tobą moim świadectwem. Prawie dwa lata temu przyszłam do kościoła, za wstawiennictwem św. Faustyny. Nie było mnie tam osiem lat (mam 20 lat), nie licząc sporadycznych sytuacji. Zanim to się stało, byłam w strasznej rozpaczy z powodu popełnionego zła, którego nie dało się już naprawić, i czułam, że nie ma nadziei. Było ze mną bardzo źle. Właśnie wtedy zwróciłam uwagę na obraz Jezusa Miłosiernego w domu kogoś z mojej rodziny. Ogarnęła mnie jakby… ufność. Jeszcze przed spowiedzią kupiłam modlitewnik św. Faustyny wraz z medali-kiem, chciałam coś o tematyce religijnej i akurat się znalazło… Nie wiedziałam nawet, kim jest św. Faustyna. Później dostałam obrazek Jezusa Miłosiernego wraz ze słowami ko-ronki do Miłosierdzia Bożego. Zaczęłam odmawiać, bo jak dostałam, to wypada… Podczas koronki czułam radość nie do opisania. Teraz wiem, że potrzebowałam Bożego Miłosierdzia rozpaczliwie – dla mnie to był naprawdę ostatni ra-tunek. Dla mnie to nie była po prostu modlitwa, od tego zależało moje szczęście w przyszłości.

Pewnego dnia pomyślałam: Jutro jadę do księdza, którego wybrałam jako spowiednika. Nie muszę się spowiadać. Muszę tam być. Oczywiście spowiadałam się i zdanie, jakie usłyszałam zostanie w moim sercu: Nie ma takiego grzechu, którego Pan Jezus by nie od-puścił. Dowiedziałam się też, że ten dzień – dzień mojej spowiedzi to 5 października – liturgiczne wspomnienie św. Faustyny”.

Moi drodzy! Spowiedź św. to niezwykły dar Miłosierdzia Bożego. To nie tylko przyznanie się do swoich grzechów, zobaczenie swej słabości i chęć poprawy. To spotkanie – spotkanie z Bożym miłosierdziem. To spotkanie pełne radości i nadziei. Spotkanie z Jezusem, który ogarnia mnie swoim miłosierdziem. I dlatego trzeba, abyśmy z sakramentu pokuty jak najczęściej korzystali. Trzeba, abyśmy jak najpełniej go przeżywali – właśnie jako spotkanie z miłosierną Miłością. Święta Teresa od Dzieciątka Jezusa tak pisze po swojej pierwszej spowiedzi św.: „Opuszczałam konfesjonał tak zadowolona, z tak lekkim sercem i z uczuciem takiej radości w duszy jak nigdy. Odtąd spowiadałam się we wszystkie wielkie święta i ilekroć przystępowałam do spowiedzi, było to dla mnie prawdziwe święto”. W kontekście tych słów czujmy się zaproszeni, aby tak właśnie przeżywać naszą spowiedź: idę na spotkanie z Jezusem, który mnie kocha nieustannie, mimo moich grzechów, i w swoim nieskończonym miłosierdziu pragnie mnie obmyć, umocnić i napełnić moje serce swoim pokojem i miłością. To jest najgłębsze przesłanie tego spotkania!

Kiedyś zapytano Apostoła Trędowatych, bł. o. Damiana, co było jego największym problemem na wyspie Molokai. A on odpowiedział, że nie lęk przed zarażeniem się trądem, ale to, że przez dłuższy czas nie miał dostępu do kapłana i nie mógł się wyspowiadać. Z kolei Adrienne von Speyr, wielka mistyczka, protestantka, została – jak sama stwierdziła – przekonana do katolicyzmu właśnie poprzez sakrament spowiedzi. Odnalazła w nim sens umierania naszego Zbawiciela, którego krzyk do Ojca Niebieskiego z krzyża był rodzajem spowiedzi w imieniu całej ludzkości. Jezus pojednał nas z Ojcem. Prawdy tej szczególnie doświadczamy, spowiadając się. Wciąż potrzebujemy się mobilizować, aby to spotkanie z Miłosierdziem przeżywać jak najlepiej. Co nam pomaga? Błogosławiony papież Jan Paweł I wspominał kiedyś, iż „myśl, że jest się półaniołem, nie przychodzi z taką łatwością, gdy wiemy, że mamy poważne wady”. A zatem tak istotny jest codzienny rachunek sumienia, kiedy uświadamiamy sobie nie tylko popełnione grzechy, ale i doszukujemy się ich przyczyny; kiedy szczerze rozmawiamy z Panem, przyznając się do słabości, i z ufnością prosimy o miłosierdzie. Obrazowo można to przedstawić tak: pranie białej koszulki. Jeśli po praniu jest śnieżnobiała, to z łatwością zauważamy na niej najmniejsze nawet zabrudzenie. Kiedy zaś pierzemy ją rzadko, to dostrzegamy tylko te duże plamy. Spotkanie z Miłosierdziem w sakramencie pokuty możemy owocniej przeżyć, jeśli z zaangażowaniem uczestniczymy w Eucharystii. Przecież w niej powtarza się i uobecnia ofiara Jezusa, który nas pojednał z Ojcem! Co więcej, w cza-sie jej celebrowania mamy przynajmniej dwa szczególne momenty – kiedy uznajemy swój grzech i prosimy o miłosierdzie. To akt pokuty na początku Mszy św. i przed Komunią św. słowa: „Panie, nie jestem godzien, abyś przyszedł do mnie, ale powiedz tylko słowo, a będzie uzdrowiona dusza moja” (por. Mt 8,5-11). Pomyśl – jak przeżywasz te dwa momenty? Z osobistym zaangażowaniem? Z uwagą? Czy może słowa te wypowiadasz automatycznie, bez „poruszenia serca”, bez szczerego odniesienia do Pana?

Moi drodzy! Skoro już mówimy o przyzwyczajeniu, rutynie, to trzeba też przypomnieć słowa Jezusa: „beze Mnie nic nie możecie uczynić” (J 15,5). Potrzebujemy Jezusa i Ducha Świętego, by odprawić rachunek sumienia, żałować za grzechy i zdecydować się na poprawę. Potrzebujemy Go – my, wyznając grzechy, ale i spowiednik, który nas rozgrzeszy. Czy pamiętamy o tym, aby do spotkania z Miłosierdziem przygotować się przez modlitwę, przez wzywanie Ducha Świętego? Inaczej może się okazać – z powodu naszego przyzwyczajenia – że na to spotkanie przyjdziemy nieprzygotowani. I co więcej, wyjdziemy z niego, nie biorąc wszystkich darów, które Pan dla nas przygotował…

A kiedy już wychodzimy z tego spotkania z Miłosiernym, to po pierwsze – nie odkładajmy pokuty, bo łatwo o niej zapomnieć. A po drugie – nie ograniczajmy się do niej. Niech dodatkowe modlitwy, jałmużna, umartwienie czy dobry uczynek staną się naszą praktyką. I to wcale nie dlatego, że pokuta najczęściej jest niewielka w stosunku do naszych grzechów – uczyńmy to z miłości i wdzięczności za otrzymaną łaskę. Za to, że Pan pozwolił nam przeżyć prawdziwe święto – święto miłości miłosiernej.

I na koniec myśl zaczerpnięta od bł. Jana Pawła I: Bóg odrzuca wady, bo są wadami, ale nie odrzuca grzesznika. W pewnym sensie to właśnie nasze wady dają Mu możliwość ukazania Jego nieskończonego miłosierdzia, nam zaś pozwalają pozostać pokornymi, a także zrozumieć wady bliźniego i mu przebaczyć. Bo – jak pisał św. Tomasz z Akwinu: „człowiek poznaje i ocenia według tego, jaki sam jest”. Z kolei św. Grzegorz z Nyssy dodaje: „Człowiek upodabnia się do Boga, gdy przebacza”.
`;