export const day9Study = `
Maryja – opiekunka i wzór Kościoła

Pielgrzymujemy już dziewiąty dzień. Dziś pokłonimy się Królowej Polski i złożymy u Jej stóp nasze intencje, trud i radość pielgrzymowania. Zawierzymy Jej siebie i tyle innych osób. Zanim to jednak nastąpi, zapraszam Was do naszej ostatniej refleksji. Będąc kilkukrotnie na Cyprze mogłem modlić się przed niezwykłą ikoną. Przedstawia ona dwie stykające się ramionami i niemal identyczne postaci Matki Bożej z Dzieciątkiem. Różnią się one między sobą kilkoma szczegółami. Jednym z nich jest to, że jedna ubrana jest w suknię czerwoną, a druga – w niebieską. Kolejną różnicą jest to, że pierwsza pochyla się do Jezusa trzymanego na prawej ręce, a ta ubrana w niebieską suknię – skłania się do Niego na lewo. Nie będę oczywiście opisywał całego bogactwa tejże ikony. Wspomnę tylko, że modlący się przed nią mówią, iż przedstawia ona całą prawdę o Maryi. Matka Boża w czerwonej szacie, symbolizującej naturę ludzką, nachyla się do Jezusa, aby szeptać mu wszystkie nasze intencje i wstawiać się za nami. Ona nas kocha i dobrze zna nasze słabości, potrzeby i nadzieje.

Papież Franciszek przypomina o tym w ten sposób: „Maryja jest zawsze uważną przyjaciółką, która czuwa i troszczy się, aby nie zabrakło wina w naszym życiu. Jest Tą, z sercem przeszytym mieczem, która rozumie wszystkie cierpienia (…). Jest misjonarką zbliżającą się do nas, by nam towarzyszyć w życiu, otwierając serca na wiarę swoim macierzyńskim uczuciem. Jako prawdziwa mama, idzie z nami, walczy razem z nami i szerzy nieustannie bliskość Bożej miłości”. Pielgrzymujemy więc: dziękując, prosząc o wybaczenie, niosąc kolejne sprawy, o których Ona będzie „szeptać” Jezusowi… Ale moi drodzy, niech to pielgrzymowanie trwa także po zakończeniu Pieszej Pielgrzymki Tarnowskiej. Mamy przecież tyle diecezjalnych sanktuariów, tych świętych miejsc, gdzie Ona czeka, wysłucha, obdarzy łaskami i pouczy. To właśnie tam zwraca się do nas, tak jak do Juana Diego: „Niech się nie trwoży twoje serce (…). Czyż nie jestem tutaj Ja, która jest twoją Matką? Wróćmy teraz do ikony z Cypru. Nie zapominajmy, że znajduje się na niej także druga postać Maryi. Jak mówią miejscowi ludzie, przypomina ona o tym, że Matka Boża nachyla się w stronę Jezusa, aby usłyszeć, czego Jezus oczekuje od nas, a potem przychodzi i mówi: „Zróbcie wszystko, cokolwiek wam powie” (J 2,5). Matka Jezusa jest także naszą kochającą Matką. Ona opiekuje się nami, broni nas i wstawia się za nami. Jednocześnie wciąż nam wskazuje właściwą drogę słuchania i naśladowania Jezusa. Maryja jest nie tylko czułą Matką, ale i najwspanialszym wzorem.

Jakże to istotne dla nas, którzy w czasie tegorocznych rekolekcji pielgrzymkowych zastanawiamy się, jak możemy być Kościołem piękniejszym, autentycznym, całkowicie oddanym Jezusowi. Maryja jest wzorem dla Kościoła, bo przez całe swe życie czyniła to, czego Pan oczekuje od nas. Przez swoje fiat z ufnością przyjęła Jezusa. Nie zatrzymała Go jednak tylko dla siebie. Zaniosła Go do Elżbiety. A potem służyła jej, wstawiała się za nowożeńcami i choć była Matką Syna Boże-go, w Nazarecie żyła pokornie, cicho i z prostotą. Na Kalwarii była przy Synu i nie przestała ufać. A potem z apostołami przyzywała Ducha Świętego.

Papież Franciszek, wskazując Maryję jako wzór dla Kościoła, zachęca: „Prosimy Ją, by swoją matczyną modlitwą pomogła nam, aby Kościół stał się domem dla wielu, matką dla wszystkich ludów i aby stały się możliwe narodziny nowego świata”. Z kolei w czasie ŚDM w Polsce, na Jasnej Górze ojciec święty wzywał: „Prośmy o łaskę, byśmy sobie przyswoili Jej wrażliwość, Jej wyobraźnię w służeniu potrze-bującym, piękno poświęcenia swego życia dla innych”.

Drodzy pielgrzymi! A teraz krótkie, misyjne wspomnienie. Kiedy byłem u sióstr misjonarek w Republice Demokratycznej Konga, pewnego dnia odwiedziliśmy lokalne maryjne sanktuarium. Było samo południe, kościół był pra-wie pusty – prawie, bo na posadzce siedziały dwie dziewczyny. Były tak skupione, że nawet nie zauważyły naszego po-jawienia się. I cały czas, z rękami uniesionymi w stronę figury Matki Bożej, powtarzały wciąż to samo zdanie: „Maryjo, pomóż mi przeżyć moją młodość tak, jak Ty przeżyłaś swoje życie”.

Moi drodzy! Kończymy tegoroczne pielgrzymowanie pod hasłem: „Żyję w Kościele”. Chcę Wam za ten wspólny czas podziękować. Za to, że jako bracia i siostry, we wspólnocie Kościoła modliliśmy się i wspieraliśmy się nawzajem. Za to, że wspólnie staraliśmy się na nowo zachwycić Kościołem, który jest naszą kochającą Matką. Dziękując, pragnę też odnieść się do modlitwy tych kongijskich dziewcząt. Życzę Wam – każdej i każdemu – aby słowa ich modlitwy stały się mottem i drogowskazem Waszego codziennego pielgrzymowania: Maryjo, pomóż mi przeżyć moje życie tak, jak Ty przeżyłaś swoje!

I na koniec prośmy o to fragmentami modlitwy papieża Franciszka:

„Dziewico i Matko, Maryjo, Ty, któraś pod tchnieniem Ducha przyjęła Słowo życia w głębi Twej pokornej wiary, całkowicie oddana Odwiecznemu, pomóż nam wypowiedzieć nasze «tak» wobec pilnej potrzeby, jak nigdy dotąd naglącej, by wszędzie rozległa się Dobra Nowina o Jezusie. Wyproś nam nowy zapał zmartwychwstałych w obecnych czasach, by nieść wszystkim Ewangelię życia zwyciężającą śmierć. Daj nam odwagę szukania nowych dróg, aby dotarł do wszystkich dar piękna, które nie zaniknie.

Ty, Dziewico słuchania i kontemplacji, Matko miłości, Oblubienico wiecznych zaślubin, wstawiaj się za Kościołem, którego jesteś najczystszą ikoną, aby się nigdy nie zamykał i nie zatrzymywał w swojej misji szerzenia Królestwa. Amen”.
`;